### ISSUE TITLE
"custom css not found"

### ISSUE THREAD

**Issue by smlombardi** [be5invis/vscode-custom-css#1]
I install extension and try to enable the css and get the above error.

I tried putting the css in my user directory and tried 

`"vscode_custom_css.file": "/users/stevel/vscode-custom-css.css"`

Am I missing something?

**Comment by be5invis** [comment]
Casing? I remembered that OS X uses `Users` instead of `users`.
This message indicates that the path does not exist.

**Comment by smlombardi** [comment]
The casing was it.  My eyes thank you for this!
