### ISSUE TITLE
Still working on 1.11.1?

### ISSUE THREAD

**Issue by pkieltyka** [be5invis/vscode-custom-css#10]
Im not seeing anything change the styles in 1.11.1, just wondering if anyone else is running into the same thing?

**Comment by be5invis** [comment]
It works, but VSCode itself would change the internal names for assigning CSSes. So you may need to update your stylesheet or modify your theme (to add support for recently-added Workbench themeing).

**Comment by pkieltyka** [comment]
thanks for the quick reply. I guess with the new workbench themeing, then eventually this extension wont be necessary?

**Comment by be5invis** [comment]
@pkieltyka This is for universal hacking. I think in a considerable period VSCode would not let you to load arbitrary CSS into it, so it is the last resort.
