### ISSUE TITLE
Not working with current VS update

### ISSUE THREAD

**Issue by AndresCampuzano** [be5invis/vscode-custom-css#104]
Neon effect is not working properly, even if I set the file's values by default.

**Comment by be5invis** [comment]
Any error messages?
Code's internal CSS classes change frequently, you may need to update your CSS too.

**Comment by mfreeman-xtivia** [comment]
I would concur that this seems to have stopped working. Used the following simple CSS file with absolutely no effect:

* {
  color: red  !important;
}

**Comment by AndresCampuzano** [comment]
> Any error messages?
> Code's internal CSS classes change frequently, you may need to update your CSS too.

Now is working, not like before, I'm gonna update my CSS, thanks.

**Comment by AndresCampuzano** [comment]
Fixed, I needed to update my CSS.
