### ISSUE TITLE
Mac installation

### ISSUE THREAD

**Issue by Siel** [be5invis/vscode-custom-css#11]
I've been trying to install the plugn into vscode on my macbook pro, but i've failed

I tried to run chown it, to run it as sudo, but the plugin simply does not install

**Comment by be5invis** [comment]
@Siel Could you please tell me the **full path** of `electron-browser/index.html` in VSCode installation?

**Comment by be5invis** [comment]
I do not have Macintosh.

**Comment by Siel** [comment]
`/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.html`

Might be that?

**Comment by f0ntana** [comment]
don't work for me too..

**Comment by be5invis** [comment]
@Siel What is the failure message? What did you do when "installing" this plugin?

**Comment by f0ntana** [comment]
for me don't have error, but the css don't load, 

my settings:

"vscode_custom_css.imports": [
   "file:///Volumes/MacintoshHD2/Developer/styles.css"
]
the file open if i click but that is not loading

**Comment by be5invis** [comment]
@f0ntana Could you paste the `index.html` in `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/`? And did you see `index.bak-customcss` in it?

**Comment by f0ntana** [comment]
I  dont ser this there i Will paste here

**Comment by be5invis** [comment]
@f0ntana 
OK, please navigate to the extension's file (https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L28), Change line 28 into this:

```
console.log(appDir, base, htmlFile, htmlFileBack)
```

Then relaunch Code, Open the developer tool, perform "Enable Custom CSS & JS", and paste the output.

**Comment by f0ntana** [comment]
https://gist.github.com/f0ntana/f64a4243128ed8d63730516f927e1145

the index.html code

**Comment by be5invis** [comment]
@f0ntana 

**Please navigate to the extension's file (https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L28), Change line 28 into this:**

```
console.log(appDir, base, htmlFile, htmlFileBack)
```

Then relaunch Code, Open the developer tool, perform "Enable Custom CSS & JS", and paste the output. If you see any other error messages, paste it here either.

**Comment by f0ntana** [comment]
![screen shot 2017-05-13 at 12 20 42](https://cloud.githubusercontent.com/assets/6570783/26027150/a530ca22-37d6-11e7-9884-3d27321327e9.png)

**Comment by be5invis** [comment]
@f0ntana 
Could you please try comment line 87, 88 and 91 in https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js and see whether it work?

**Comment by f0ntana** [comment]
i comment this lines

`// var updated = hasBeenUpdated(statsBak, statsOr);
// if (updated) {
// some update has occurred. clean install
// cleanInstallFunc();
// }``

**Comment by be5invis** [comment]
@f0ntana 
………………
**Line 90, ` cleanInstallFunc();`, should not be commented.**

**Comment by f0ntana** [comment]
now i uncomment, and nothing change

**Comment by f0ntana** [comment]
![screen shot 2017-05-13 at 14 04 32](https://cloud.githubusercontent.com/assets/6570783/26027946/1ffd5758-37e5-11e7-9d13-886b9596edb1.png)

**Comment by be5invis** [comment]
@f0ntana It is strange.
Change the function starting from line 69 into this:

```js
	function cleanCssInstall() {
console.log('START BACKUP');
		var c = fs.createReadStream(htmlFile).pipe(fs.createWriteStream(htmlFileBack));
		c.on('finish', function () {
console.log('START INSTALL');
			replaceCss();
console.log('FINISH INSTALL');
		});
	}
```
Restart Code, open the developer panel, run the "enable CSS" command, see what is shown in developer panel.

**Comment by f0ntana** [comment]
![screen shot 2017-05-13 at 14 14 30](https://cloud.githubusercontent.com/assets/6570783/26028041/a3164130-37e6-11e7-8e8a-58e0a698058b.png)

**Comment by be5invis** [comment]
@f0ntana It is strange. The code successfully patched the file but does not work.
You have dev tools opened right? switch to Networks, press F5, and paste the URL and content (in the Response panel) of the first request (should be `.../index.html?...`).

**Comment by be5invis** [comment]
@f0ntana and, PLEASE, paste the corresponded `electron-browser/bootstrap/index.html` again.

**Comment by f0ntana** [comment]
![screen shot 2017-05-13 at 14 25 57](https://cloud.githubusercontent.com/assets/6570783/26028135/1dadc1ba-37e8-11e7-8f98-3d0865e53fef.png)

**Comment by be5invis** [comment]
@f0ntana Click the first item, show me the **DETAILS**.

**Comment by be5invis** [comment]
@f0ntana And I saw errors. **CLICK THE "Console", SHOW ME THE RESULTS.**

**Comment by f0ntana** [comment]
![screen shot 2017-05-13 at 14 27 06](https://cloud.githubusercontent.com/assets/6570783/26028143/60499f44-37e8-11e7-922c-d9cb1b2e655e.png)


now its show but Code give me this error
![screen shot 2017-05-13 at 14 29 16](https://cloud.githubusercontent.com/assets/6570783/26028152/95fcd0c0-37e8-11e7-8f87-555b9ae6da83.png)


and this is the details

![screen shot 2017-05-13 at 14 29 08](https://cloud.githubusercontent.com/assets/6570783/26028153/9df03cf4-37e8-11e7-81f6-69c031aa2470.png)

**Comment by f0ntana** [comment]
this error start before run the command enable CSS

**Comment by be5invis** [comment]
@f0ntana
So, the patch works. And I saw the CSS is loaded. 
But it does not work?
What is in the CSS?

**Comment by f0ntana** [comment]
`.type.storage,.type.storage.declaration, .storage.class.modifier {
  font-family: 'flottflott';
  font-size: 1.7em;
}

.type.storage.arrow.function {
  font-family: 'Fira Code'
}

.decorator.name, .decorator.punctuation:not(.block), .import.keyword {
    font-family: 'flottflott';
    font-size: 1.7em;
    color: #68f39b!important;
}
.attribute-name {
    font-family: 'flottflott';
    font-size: 1.5em;
}

.html.quoted.double {
    color: #a6f3a6!important;
}
.comment {
	color: #c5c5fd!important;
}
.comment:not(.punctuation) {
    font-family: flottflott;
    font-size: 1.5em;
}`

**Comment by be5invis** [comment]
@f0ntana Looks that your CSS is depending on some classes that does not exist anymore for the current VSCode version :(

**Comment by be5invis** [comment]
@f0ntana See #10.

**Comment by f0ntana** [comment]
u know the corrects css ?

**Comment by be5invis** [comment]
@f0ntana CSS classe used for syntax highlight is now **dynamically generated**. So I do not know or predict.

**Comment by be5invis** [comment]
@f0ntana #9 may have a better explanation.

**Comment by f0ntana** [comment]
ahhh i see now, work for me!

![screen shot 2017-05-13 at 14 43 21](https://cloud.githubusercontent.com/assets/6570783/26028241/8aca35f6-37ea-11e7-9038-c25e34182cb8.png)


thanks for help

**Comment by davidwu220** [comment]
@f0ntana How did you fix it? I'm having the same issue

**Comment by jbouhier** [comment]
@davidwu220 Read #9 to fix it.

**Comment by armchairdeity** [comment]
@jbouhier - I had everything right except running `Enable Custom CSS and JS` from the Command Palette... that seemed to be the piece I was missing. Your instructions were awesome.
