### ISSUE TITLE
Custom CSS and JS not being applied

### ISSUE THREAD

**Issue by 2leo2** [be5invis/vscode-custom-css#118]
I'm trying to use themes with custom css and js and it worked until it updated. I tried everything in the custom css and js github page and vs code page but it still doesn't work

**Comment by eXigentCoder** [comment]
On macos here, having the same thing, just stopped working yesterday, things I tried which didn't work:

- Disable then enable the extension and reload
- reverting to `3.0.8`
- Uninstalling and reinstalling
- restarting VSCode
- restarting my laptop

Settings.js file:
```
  "vscode_custom_css.policy": true,
  "vscode_custom_css.imports": [
    "https://gist.githubusercontent.com/eXigentCoder/5d51dd97d643e118b30094dbf57225ed/raw/54c6dd2ccf682d5eb48c3aeacbfd30827b3b29df/synthwave-x-fluoromachine.css"
  ],
```

**Comment by divyanshu013** [comment]
Facing same issue on my linux machine as well.

**Comment by lacostenycoder** [comment]
Same problem today. Was working then stopped after I reinstall and did `chown` on electron.  ¯\_(ツ)_/¯

**Comment by thisVioletHydra** [comment]
```
  "vscode_custom_css.policy": true,
  "vscode_custom_css.imports": [
    "https://gist.githubusercontent.com/thisVioletHydra/a20a57269df1d91b91760ed09e325f8a/raw/b50e670fed503ca02ab47f4f2e2e181aa8f61cd0/.vscodestyles.css"
  ],
```

## not working ¯\_(ツ)_/¯

**Comment by eXigentCoder** [comment]
So I uninstalled VSCode and tried to get it working again, found something interesting, it won't load when I try reference the file from [GitHub](https://gist.githubusercontent.com/eXigentCoder/5d51dd97d643e118b30094dbf57225ed/raw/54c6dd2ccf682d5eb48c3aeacbfd30827b3b29df/synthwave-x-fluoromachine.css) even if I have added it as a trusted domain but works fine if the file is locally on my machine.

**Comment by divyanshu013** [comment]
I've figured out the solution for my Linux machine. I had installed from `snap`. Removed that and installed from `dnf`. Now custom CSS is working perfectly.
