### ISSUE TITLE
Selectors ?

### ISSUE THREAD

**Issue by melMass** [be5invis/vscode-custom-css#12]
Hi,

Thanks for the extension!
I'm trying to mix and match different fonts based on types. 
It seems that the selectors are not specific enough in the current version of VScode (.mtk**xx**) and can't find a reference on those new selectors. do you have any ?
Or is there a way to access theme selectors like `.storage.class.modifier` or `.token.keyword.operator`?

Thanks

**Comment by be5invis** [comment]
@melMass 
Currently there is no method to predict `.mtkxx`. It is dynamically generated from `tmLanguage` files.
Custom CSS & JS only gives you the ability to load arbitrary CSS/JS into Code's window. Other correctness is not guaranteed.

**Comment by melMass** [comment]
that's what i thought thanks.
I guess I'll have to go the Yaml way 😢 :)
