### ISSUE TITLE
Custom CSS not injected in 1.48.0-insider version

### ISSUE THREAD

**Issue by mauricecruz** [be5invis/vscode-custom-css#125]
Since updating to `1.48.0-insider`, custom css no longer loads.

**Comment by irinna77** [comment]
I can confirm, my custom css solution to multirow tabs broke with this update

**Comment by be5invis** [comment]
I cannot reproduce this in 1.48.0. Reloading just worked (on my system).

**Comment by davidpetrey** [comment]
Trying this for the first time and it's not working. 
![image](https://user-images.githubusercontent.com/13895170/91895719-50353780-ec5d-11ea-8d5b-fd4c21ba17a0.png)

**Comment by ZayRTun** [comment]
Yep, I can confirm that it's not working with version 1.48.2
