### ISSUE TITLE
Leverage vscode settings sync

### ISSUE THREAD

**Issue by swrobel** [be5invis/vscode-custom-css#126]
Now that [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) is generally available, is there a way to set this extension up so I don't have to manage individual css files on each of my machines, but instead have my css automagically sync between them?

**Comment by Buckwich** [comment]
I use a Github repo (https://github.com/Buckwich/vscode-custom-css-snippets) to store my custom css, one could also use gists. As the extension takes the files as URLs, the links to raw github files can be synced. I still have to do a CSS reload on every machine though.
