### ISSUE TITLE
windows 10 - vscode corrupted [Unsupported] after uninstall

### ISSUE THREAD

**Issue by veglos** [be5invis/vscode-custom-css#128]
Issue

- vs code stays unsupported [Unsupported] after uninstall on windows
- codicon-paintcan is still being displayed in the vscode's status bar.

Attempts

1. tried to reinstall and uninstall extension with elevated privileges (as administrator)
2. tried to reinstall and uninstall extension without elevated privileges (as administrator)

**Comment by be5invis** [comment]
This is by design. This extension modifies VSCode **itself** so it will complain about it is "corrupted".
Close as by design.

**Comment by AZeed18** [comment]
> This is by design. This extension modifies VSCode **itself** so it will complain about it is "corrupted". Close as by design.

I made the corruption notification "Don't show again", how to undo that? (I want to allow the notification again and uninstall the extension)
