### ISSUE TITLE
'Custom CSS/JS Loaded' indicator takes up a lot of space in the statusbar

### ISSUE THREAD

**Issue by kazdegroot** [be5invis/vscode-custom-css#13]
The indicator introduced in 6408e7b243aced36ab6a8428dd82b678fd862424 takes up a lot of space, for the amount of information it supplies.

Personally, I think the [Unsupported] in the title bar is information enough to show the extension is working, but I understand the want for something more concrete. 

Please just give an option to disable it, or at least reduce it to an icon.

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/26201604/649efad6-3c06-11e7-982e-5192b8b0783e.png)
This would be better

**Comment by kazdegroot** [comment]
That looks very nice

**Comment by be5invis** [comment]
Would be included in next version. closed.
