### ISSUE TITLE
not able to load css from file protocol in insider 1.54

### ISSUE THREAD

**Issue by liangch** [be5invis/vscode-custom-css#135]
In this insider version, the css file is not able to load by file protocol (file://).  Copied the css file to a web server, and use http://, it works.

Version: 1.54.0-insider
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

**Comment by willcode4food** [comment]
I tried serving this up from a Gist and couldn't get it to work.

**Comment by BinWu-859** [comment]
I relocated the css file to ~/.vscode/extensions and it works.

**Comment by denis-gorin** [comment]
> I relocated the css file to ~/.vscode/extensions and it works.

+1

**Comment by be5invis** [comment]
@BinWu-859 If you'd like you could file a PR to update the README for this. Looks like a permission issue.

**Comment by be5invis** [comment]
Or maybe write some copy logic...

**Comment by BinWu-859** [comment]
> @BinWu-859 If you'd like you could file a PR to update the README for this. Looks like a permission issue.

It is not related with permission.
https://github.com/microsoft/vscode/pull/116522/commits/8e7eca21577ca98c6d8cf33bd594fb17b1fe2b15 made the differece

**Comment by be5invis** [comment]
It should work now in V5, as the CSS/JS files will be now **copied to the extension dir**.
