### ISSUE TITLE
Running Reload Results in an Error, v1.54.1

### ISSUE THREAD

**Issue by luketevers** [be5invis/vscode-custom-css#136]
I just noticed this this morning, my vscode is running on:
<img width="241" alt="Screen Shot 2021-03-05 at 11 00 59 AM" src="https://user-images.githubusercontent.com/24533114/110161390-255da480-7da2-11eb-8b5b-e61ec26e3ee5.png">
And I'm seeing this error:
<img width="512" alt="Screen Shot 2021-03-05 at 10 57 55 AM" src="https://user-images.githubusercontent.com/24533114/110161429-30b0d000-7da2-11eb-891f-a21880b973e9.png">

**Comment by be5invis** [comment]
What are the logs you found? (`cmd-shift-p` -> Search `Show Logs` -> `Extension Host`)

**Comment by luketevers** [comment]
<img width="1234" alt="Screen Shot 2021-03-05 at 11 50 52 AM" src="https://user-images.githubusercontent.com/24533114/110166457-3bbb2e80-7da9-11eb-8c6e-1f7bc64bcb64.png">
Looking at this it might be a permissions error, not sure if that's on the extension's end or my local's

I did run `sudo chown -R (whoami) /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`, it didn't help, but I'm thinking this should have given the app admin privileges. Could also be totally wrong tho

**Comment by luketevers** [comment]
This appears to be resolved
