### ISSUE TITLE
Content Security Policy violation error 

### ISSUE THREAD

**Issue by tbusser** [be5invis/vscode-custom-css#14]
Hi, 

I'm trying to use your plugin but it isn't working for me. I'm using Visual Studio Code version 1.14.0 on OSX 10.12.5.  I've tracked it down to the following error:
![image](https://user-images.githubusercontent.com/5519027/28166937-1be1a726-67da-11e7-9fa0-8c0eb08f390b.png)
I've tried to modify the index.html but it looks like it gets regenerated and thus undoing my changes. Is this an issue you're aware of and is there a workaround?

**Comment by be5invis** [comment]
This tag is for the "bucket" indicator on the status bar.
The last commit fixed that. Would publish it tomorrow.
Closed.
