### ISSUE TITLE
Can't load CSS in vscode 1.58

### ISSUE THREAD

**Issue by arucuenca** [be5invis/vscode-custom-css#148]
Yesterday I updated my vscode and repeated the "after-update" routine:
1- Disable custom CSS;
2- Restart vscode;
3- Enable custom CSS;
4- Restart vscode;

After that, the "Your vscode instalation seems to be broken" message didn't appear (as it always did when I enabled the loader), and the CSS from the theme I use wasn't loaded (the location I provided to `"vscode_custom_css.imports"` in User Settings is still the same and points to the same file).

Is there a way to debug this so I can provide more information?

Thank you guys for the gret extension!

**Comment by mijlouis** [comment]
Same here. 
Fixed it with the workaround mentioned in issue #144 

Copied my style modifications e.g. file `style.css` locally to folder 
`c:\Users\<your-user-name>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench`

and added a link to that css file to 

`workbench.html`

which is in the same folder,

My `workbench.html` looks now basically like this 

```html
<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
	</head>
	<body aria-label="">
	</body>

	<!-- Init Bootstrap Helpers -->
	<script src="../../../../bootstrap.js"></script>
	<script src="../../../../vs/loader.js"></script>
	<script src="../../../../bootstrap-window.js"></script>

	<!-- Startup via workbench.js -->
	<script src="workbench.js"></script>
	<link rel="stylesheet" href="style.css"/>
<!-- !! VSCODE-CUSTOM-CSS-SESSION-ID ae913ab6-b1a1-4d32-9653-b51405df7f83 !! -->
<!-- !! VSCODE-CUSTOM-CSS-START !! -->
<!-- !! VSCODE-CUSTOM-CSS-END !! -->
</html>
```

In the developer tools of vscode I also saw that the linked file provided by the extension in the VSCODE-CUSTOM-CSS cannot be loaded
![image](https://user-images.githubusercontent.com/43267376/125066428-4701cc00-e0b3-11eb-9da9-c501cde7cd87.png)

![image](https://user-images.githubusercontent.com/43267376/125066202-02763080-e0b3-11eb-8b6a-f9128fd48d86.png)

**Comment by philgran** [comment]
I had the same problem, pathing on OSX looks more like this:
`/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench`

**Comment by iambudi** [comment]
I could not locate `workbench.html` in Big Sur, so i add my custom css directly in file `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.css` as pointed by @philgran as temporary workaround.
