### ISSUE TITLE
Removing [Unsupported] from the titlebar

### ISSUE THREAD

**Issue by fabiospampinato** [be5invis/vscode-custom-css#15]
I've made an [extension](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-no-unsupported) for removing the [Unsupported] text from the titlebar, it appears after enabling this extension.

I think it would be pretty common to wish to be able to remove it after installing your extension, so maybe adding a link to it in the readme could be a good idea, what do you think?

**Comment by be5invis** [comment]
No.
This extension **alters VSCode itself** and **may have the risk to make it malfunction**. Therefore I choose to preserve that message.
You should tell the VSCode team to have an option to remove that.
Closed.

**Comment by fabiospampinato** [comment]
I already opened an [issue](https://github.com/Microsoft/vscode/issues/30556) but they have different opinions.

**Comment by lehni** [comment]
For those who are bothered by this. I have created an extension to adjust internal checksums to the reflect the modifications:

https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums
