### ISSUE TITLE
Extension no longer works on macOS Monteray + VS Code 1.62.3?

### ISSUE THREAD

**Issue by JohnKurlak** [be5invis/vscode-custom-css#156]
After updating to VS Code 1.62.3 on macOS Monteray, the extension no longer works for me. It looks as if `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.html` no longer exists. I just see `workbench.desktop.main.js` and `workbench.desktop.main.css`. Do we need a fix similar to the one for https://github.com/be5invis/vscode-custom-css/issues/148?

**Comment by carljohnesan** [comment]
Same issue, though I'm on High Sierra

**Comment by katerlouis** [comment]
I'm on VS Code 1.63.2 on my new M1 Max Macbook Pro 16'' with altest macOS Monteray and also can't get my setup to work again :(

**Comment by iambudi** [comment]
Mine is working fine on 1.63.2 M1. Just need to adjust the css classes in my custom style css file following 1.63.2 via developer tool inspect element.

**Comment by fharper** [comment]
I have the same issue on 1.63.2 macOS Monterey 12.1 even when adjusting some CSS classes that changed 😅

**Comment by fharper** [comment]
For now I just add my code in `workbench.desktop.main.css` directly and ignore the "corrupt" message.

**Comment by katerlouis** [comment]
> Mine is working fine on 1.63.2 M1. Just need to adjust the css classes in my custom style css file following 1.63.2 via developer tool inspect element.

I don't understand how that's possible. Like OP points out: workbench.html doesn't exist anymore.

**Comment by kotx** [comment]
Same issue.
