### ISSUE TITLE
[Feature request] write css in config file directly

### ISSUE THREAD

**Issue by mashirozx** [be5invis/vscode-custom-css#157]
既然现在也是以inline的形式注入的，那么何不考虑一下直接支持在配置文件里面书写css，无非也就是当做一个字符串处理，这样的好处是便于同步，切换设备的时候不用再考虑迁移本地的样式文件。

**Comment by be5invis** [comment]
You can't. VSCode literally blocks all external file references now. See #148.
Closing.

**Comment by mashirozx** [comment]
Does that mean this plugin won't be maintained anymore?

**Comment by be5invis** [comment]
Well, VSCode currently blocks _all_ external CSS/JS unless it is inlined. So your feature request is not doable.

**Comment by mashirozx** [comment]
Well, I mean something like this:

```jsonc
// settings.json
{
  "vscode_custom_css.imports": "body { background: yellow; }",
}
```

**Comment by be5invis** [comment]
That should be under another property...

**Comment by mashirozx** [comment]
haha

**Comment by be5invis** [comment]
But do you really think it is a good idea? Currently, the extension is able to load web resources (you _can_ write `http://your-sync-disk/whatever.js` in `imports`).

**Comment by mashirozx** [comment]
Not working here...
![image](https://user-images.githubusercontent.com/16148054/143412331-cd0b96d6-ecfe-48af-9e60-51e6d1b535e5.png)

**Comment by be5invis** [comment]
Do you have error messages (`Ctrl-Shift-I`)

**Comment by mashirozx** [comment]
No error from this plugin
![image](https://user-images.githubusercontent.com/16148054/143413030-805abe70-9140-4161-b310-a7fa2172c664.png)
![image](https://user-images.githubusercontent.com/16148054/143413144-19a1b9a6-bd86-4dec-967c-985ab38ef4df.png)

**Comment by be5invis** [comment]
Please execute `Enable Custom CSS and JS` and see whether there are any error messages.

**Comment by mashirozx** [comment]
Still the same

**Comment by mashirozx** [comment]
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by be5invis** [comment]
Hmm the extension failed to load your file. Reason
```
FetchError: request to https://ngx.moezx.cc/share/vscode-injection-css.css failed, reason: certificate has expired
```

**Comment by mashirozx** [comment]
Wow, thanks a lot, I've disabled the https, and it works fine. 💖
