### ISSUE TITLE
Failed to load resource:net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by nealhnguyen** [be5invis/vscode-custom-css#16]
<img width="399" alt="capture" src="https://user-images.githubusercontent.com/6827627/28853671-049ed3e2-76e7-11e7-8b3a-7c2f1fd5ab79.PNG">

How do I fix these two errors?

**Comment by be5invis** [comment]
If you are on Windows, add the disk letter (`file:///C:/Users/...`).
