### ISSUE TITLE
How to remove the [Unsupported] text in Vscode's title

### ISSUE THREAD

**Issue by heweicong** [be5invis/vscode-custom-css#167]
![1658908812697](https://user-images.githubusercontent.com/25929134/181194221-638d7bb4-ec43-4697-8b9a-4c0e56614036.png)

**Comment by be5invis** [comment]
You can't. This plugin will always modify the VSCode itself.

**Comment by TheRedBandiCoot** [comment]
> 1.Install the extension "Fix VSCode Checksums"
> 2.Open the command palette (Ctrl + Shift + P) and then write and select "Fix Checksums: Apply"
> 3.Finally, close VS Code and open it again.

[Original Source ](https://stackoverflow.com/questions/62845918/visual-studio-code-unsupported-not-resolved)

**Comment by TheRedBandiCoot** [comment]
> ![1658908812697](https://user-images.githubusercontent.com/25929134/181194221-638d7bb4-ec43-4697-8b9a-4c0e56614036.png)

> 1.Install the extension "Fix VSCode Checksums"
> 2.Open the command palette (Ctrl + Shift + P) and then write and select "Fix Checksums: Apply"
> 3.Finally, close VS Code and open it again.

[Original Source ](https://stackoverflow.com/questions/62845918/visual-studio-code-unsupported-not-resolved)

**Comment by heweicong** [comment]
> > ![1658908812697](https://user-images.githubusercontent.com/25929134/181194221-638d7bb4-ec43-4697-8b9a-4c0e56614036.png)
> 
> > 1.Install the extension "Fix VSCode Checksums"
> > 2.Open the command palette (Ctrl + Shift + P) and then write and select "Fix Checksums: Apply"
> > 3.Finally, close VS Code and open it again.
> 
> [Original Source ](https://stackoverflow.com/questions/62845918/visual-studio-code-unsupported-not-resolved)

awesome~~ !!
