### ISSUE TITLE
command 'extension.updateCustomCSS' not found

### ISSUE THREAD

**Issue by ctf0** [be5invis/vscode-custom-css#168]
```
Version: 1.70.0-insider
Commit: b4d5b4ed69af953901051b1f049851b9dca3563e
Date: 2022-07-28T05:16:00.371Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0
```

```
Command 'Reload Custom CSS and JS' resulted in an error (command 'extension.updateCustomCSS' not found)
```

**Comment by kimiyuki** [comment]
Hi, I got the same error message.
I am using code-insider(version1.70).
But, when I used code(version1.69), there was no error.

**Comment by taeuba** [comment]
I have the same error. I noticed that I had to update the extension's staging dir filepath in VSCode extension settings due to new version of custom CSS loader but that did not solve the error.

**Comment by be5invis** [comment]
Are there messages visible from Code's Developer Tool console?

**Comment by ctf0** [comment]
it pretty much says the same thing :(

**Comment by be5invis** [comment]
Version 7 is targeting `^1.70.0` version of VSCode. I do not know whether Insider version influence that...

**Comment by chris-crowson** [comment]
Hello Version: 1.70.0 of VSCode is now live.  After updating, I am consistently running into this error.

**Comment by be5invis** [comment]
Do you have logs at the developer tools?

**Comment by euphbriggs** [comment]
I'm experiencing this issue as well. The screenshot below shows my current logs from the developer tools. If I can provide any info, please let me know. I'm happy to help.

<img width="1051" alt="Screen Shot 2022-08-04 at 2 25 15 PM" src="https://user-images.githubusercontent.com/20155143/182936236-06bbc120-f643-4eb5-9650-733b9d61dcb2.png">

**Comment by be5invis** [comment]
Oh, `node-fetch`.
I shall stay with old version for now.

**Comment by lainbo** [comment]
`command"extension.updateCustomCSS not found`
I encountered the same error in 1.7.0

**Comment by euphbriggs** [comment]
I confirm this fixed the issue I was seeing. Thanks for the quick fix! This extension is nice to have.

**Comment by chris-crowson** [comment]
Confirmed this fixed it for me as well.  Thanks for the fast turn around!

**Comment by taeuba** [comment]
Confirming fixed for me too, thank you for the fix!

**Comment by KKRAKOVIA** [comment]
@be5invis i just wanna say thank you.
Didn't knew i was so addicted to this extension.
