### ISSUE TITLE
As of VS Code 1.70.1 this extension is not working

### ISSUE THREAD

**Issue by JustinLebo** [be5invis/vscode-custom-css#169]
I just updated to VS Code 1.70.1 today. I'm familiar with the process of running `Reload Custom CSS and JS` in the VScode prompt. 

However today the command `Reload Custom CSS and JS` isn't there. I tried to uninstall/reinstall the extension, but to no avail. My custom scripts are no longer being loaded at runtime, and the plugin doesn't seem to expose anything VScode recognizes.

**Comment by be5invis** [comment]
There was #168. Perhaps you need to update the version of the extension

**Comment by JustinLebo** [comment]
Not sure what happened, I restarted my mac and the command is back. It must have been a problem on my end, apologies.
