### ISSUE TITLE
[Extension Host] (node:9908) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by nealhnguyen** [be5invis/vscode-custom-css#17]
![image](https://user-images.githubusercontent.com/6827627/28935768-74cafd0e-783a-11e7-86f4-e95be3019cb4.png)

Hello, what do you think of this error?

**Comment by be5invis** [comment]
My code does not even use `os.tmpDir`. This is external.
Closed.
