### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Gumbobrot** [be5invis/vscode-custom-css#176]
where is settings.json?

**Comment by Dinosaurum** [comment]
i just wanna make this vs code shit don't look like that crap they did and just add a theme and i have to be a master hacker installer god just to do this

**Comment by MohnishMagesh** [comment]
Press F1 or Ctrl+Shift+P to open command palette, then type settings.json, then you should press Preferences: Open User Settings (JSON)
![image](https://user-images.githubusercontent.com/52004413/209050369-050d09bb-0e2b-4eb9-979c-5862aba447ee.png)
