### ISSUE TITLE
Shows Info: Run VS Code with admin privileges so the changes can be applied

### ISSUE THREAD

**Issue by s7dhansh** [be5invis/vscode-custom-css#18]
I am unable to enable the extension on linux (ubuntu 17.04). It always gives an info message to run it as admin. Why does it need admin privilege when it `code` is being run as a normal user?

**Comment by be5invis** [comment]
This extension **alters Code itself** so you need permission to change the Code.

**Comment by s7dhansh** [comment]
Ok thanks.

**Comment by Hugofsp93** [comment]
I had the same problem, but this question donut seems to help in really matters.

**Comment by ZXMLoveCXF** [comment]
> This extension **alters Code itself** so you need permission to change the Code.

so How can I authorize vscode?

**Comment by s7dhansh** [comment]
Try opening it via root/admin user (eg. sudo)

**Comment by RazaGR** [comment]
I Have this issue with vscode-sshfs extension, the developer mentioned the cause

@be5invis  is there any solution available?
https://github.com/SchoofsKelvin/vscode-sshfs/issues/131#issuecomment-485914270
> When you remote your ssh fs, it opens `ssh://sharif-camera/` as WorkspaceFolder. The extension probably assumes every WorkspaceFolder is on the local drive, and tries to access `/sharif-camera` _(or something like `/sharif-camera/some-css-extension-file.ext`)_. That directory doesn't exist, so the OS throws a Permission Denied error or something, which is what the extension thinks is the problem.
> 
> Since the problem isn't caused by this extension, I'll be closing this issue. You should probably report this issue to the developers of the vscode-custom-css extension if you want this to get fixed.

**Comment by RezhaBlue** [comment]
chiming in here as well. I'm running into the same issue, this was closed with no explanation or anyone addressing it. I have tried both wsl and windows using sudo and run as admin respectively but the extension continues to assert I need to run vs code with admin privileges. This seems like a bug to me.

**Comment by victorbrambati** [comment]
this extension does not work if you downloaded the vscode with snap

**Comment by sundowatch** [comment]
@victorbrambati 's solution works for me.
