### ISSUE TITLE
snap vscode on linux

### ISSUE THREAD

**Issue by vinaooo** [be5invis/vscode-custom-css#184]
hi
I cant activate the custom CSS, i think this is due to SNAP instalation on linux, maybe this is a permission problem

**Comment by AshkanV** [comment]
Hello
Use these instructions:
https://askubuntu.com/questions/919091/why-cant-snap-files-be-modified-in-any-way

For example:
``` bash
path="/snap/code/current/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/"
mkdir -p "${HOME}${PATH}"
cp "${PATH}" "/home${PATH}"
mount --bind "${HOME}${PATH}" "${PATH}"
```

and use the service described from the above link to make the mounting procedure automatic
