### ISSUE TITLE
Won't Remove Custom CSS

### ISSUE THREAD

**Issue by secondmanveran** [be5invis/vscode-custom-css#185]
I followed the instructions implicitly and now I can't get this custom css off my themes.

No backup was made of Electron as you state will happen on your extension page, so now I assume that my entire editor is botched?

Any help would be appreciated.

**Comment by BabcB** [comment]
you could use 'Disable Custom CSS and JS' option to remove the custom CSS

**Comment by shaggyfeng** [comment]
> 

Me too, I have to use insider just to remove the CSS... I know I am a noob, but did not expect Disabling failed...
