### ISSUE TITLE
Doesn't seem to be working with latest VSCode update 1.78.0 (on Linux at least)

### ISSUE THREAD

**Issue by 0xZaphod** [be5invis/vscode-custom-css#187]

**Comment by calebHankins** [comment]
Same on Mac. Getting a "Run VS Code with admin privileges so the changes can be applied." after running code via sudo.
 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/11457315/236236054-cccc7e5e-6922-4325-aadd-e44007fdafc8.png">

**Comment by faceair** [comment]
<img width="1352" alt="image" src="https://github.com/be5invis/vscode-custom-css/assets/3659110/3976c21c-f743-477d-a964-83f328e082ef">
I see this error from the console.

**Comment by ruudhanegraaf** [comment]
> <img alt="image" width="1352" src="https://user-images.githubusercontent.com/3659110/237151281-3976c21c-f743-477d-a964-83f328e082ef.png"> I see this error from the console.

Ditto on Windows.

**Comment by ruudhanegraaf** [comment]
Thanks, be5invis! :-)

**Comment by calebHankins** [comment]
Thanks for the quick turnaround!

**Comment by JustinLebo** [comment]
Is this commit released? I am still seeing this problem with the latest version of the extension (7.2.0).

**Comment by jgspratt** [comment]
@faceair @ruudhanegraaf - I am brand new to VSCode, and I don't know how to get that debug console message to show up.  I tried running `View: Toggle Debug Console` but nothing showed up there.  What do I need to do?  I think I may be having a similar issue and I wanted to gather this.

**Comment by ruudhanegraaf** [comment]
Hi @jgspratt. You should see it by going to 'Help | Toggle Developer Tools' or using the command `Developer: Toggle Developer Tools`. That will display the developer tools window we all know and sometimes love, sometimes hate from Chrome/Chromium/Edge, only in this case for the VSCode instance. :-)
