### ISSUE TITLE
Inline Scripts are not executing due to updates VS code made to the security policy

### ISSUE THREAD

**Issue by JustinLebo** [be5invis/vscode-custom-css#189]
VS code added the following meta tag to the workbench on a recent update:

    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' https: data: blob: vscode-remote-resource:; media-src 'self'; frame-src 'self' vscode-webview:; object-src 'self'; script-src 'self' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline'; connect-src 'self' https: ws:; font-src 'self' https: vscode-remote-resource:;">

This prevents inline scripts from running, and the console throws the following error:

    workbench.html Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' blob:". Either the 'unsafe-inline' keyword, a hash ('sha256-+5pI7lA9hEyffj2KyiB9IDlleMhqQnHqibn5AdEi+8w='), or a nonce ('nonce-...') is required to enable inline execution.

Is there a way to update this extension to add the script tags with the unsafe-inline keyword?

**Comment by be5invis** [comment]
Dupe of #187. Resolve as already fixed.

**Comment by JustinLebo** [comment]
Is this commit public? I'm still seeing this issue with the latest build.
