### ISSUE TITLE
Custom CSS run as Standard User ?

### ISSUE THREAD

**Issue by SheepDomination** [be5invis/vscode-custom-css#193]
I always run Visual Studio Code as a standard user; rather then an administrator user. Although in order to use some scripts but not just some scripts but it is suggested that custom css be run in administrator mode. Can an option or could this requirement be bypassed so that scripts that depend on custom css be run even as a standard user ?

**Comment by SheepDomination** [comment]
I'm trying to run an extension that even if I start visual studio code as an administrator to enable custom css, when running visual studio code as a standard again custom css is not enabled. If this was the case, the extension that depends on custom css would work, that is the issue.

**Comment by be5invis** [comment]
This extension **modifies VSCode itself**, so you need proper permission when you apply changes. After you applied the changes you can switch back to normal user.

**Comment by SheepDomination** [comment]
> This extension **modifies VSCode itself**, so you need proper permission when you apply changes. After you applied the changes you can switch back to normal user.

From what I've seen, even when giving the extension proper permissions as in Administrator privileges; this doesn't carry over when loading visual studio code in a standard user ?
