### ISSUE TITLE
Relative path support

### ISSUE THREAD

**Issue by HolbyFPV** [be5invis/vscode-custom-css#194]
I'm using vscode setting sync, and the other PC which I am synced on has a different username.  My dotfiles repo is installed on my home directory.  I'd like to use relative pathing in `vscode_custom_css.imports` but there doesn't seem to be any support.  I also tried using ENV variables like $HOME and %USERPROFILE% with no luck.  

Could you add support for either relative pathing or environment variables?

**Comment by ian-h-chamberlain** [comment]
As an alternative to / expansion on this, supporting [VSCode variables](https://code.visualstudio.com/docs/editor/variables-reference) would be nice, and is consistent with most other extensions. I guess technically that's a superset but at least `${userHome}` or `${env:HOME}` would work for this use case. (Some use cases might also want `${workspaceFolder}`, not sure?)

**Comment by Eigen-Lotus** [comment]
So VSCode variables just aren't supported right now?  (I did try for instance, `"file:///${userHome}/.config/VSCodium/User/custom.css"` for `vscode_custom_css.imports`, but sadly didn't work, and I was not sure if it was just because I wasn't using the vscode variables properly)

I was finding a solution to this as well, because I didn't want to hardcode in my username for one machine in my `settings.json` since I plan on using the same config on other machines.

**Comment by ian-h-chamberlain** [comment]
As far as I can tell, neither env variables nor VSCode variables are supported. I've been using a configuration like this to work around this (just specifying every possible home dir I can think of):
```jsonc
    "vscode_custom_css.imports": [
        "file:///home/deck/.config/Code/User/custom.css",
        "file:///Users/ichamberlain/.config/Code/User/custom.css",
        "file:///Users/ianchamberlain/.config/Code/User/custom.css",
	]
```
The downside is that it creates a warning for all the paths that don't exist, and any time I use VSCode on a new device I have to add its home dir there. Having proper variable support would be a much cleaner solution for sure.

**Comment by ian-h-chamberlain** [comment]
I'd personally still love to see either this or #199 implemented for easier cross-platform support. If the maintainer(s) are open to it I could take a stab at adding variable interpolation support with https://www.npmjs.com/package/vscode-variables

**Comment by HolbyFPV** [comment]
![image](https://github.com/be5invis/vscode-custom-css/assets/61704528/b5dacda6-d73a-42fe-9df3-bbcd7a4cdb5c)

I am now using Apc Customize++ to solve this.  No more need for custom css or the annoying corrupted popup.  
Full [.dots](https://github.com/HolbyFPV/.dotfiles/blob/main/mirrors/vscode/settings.json) for reference.

**Comment by ilteris** [comment]
@HolbyFPV thank you so much!!!
