### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by BrandonKirbyson** [be5invis/vscode-custom-css#198]
Hi, I have an extension I made that uses this as a dependency. It is called [VSCode-Animations](https://github.com/BrandonKirbyson/VSCode-Animations) and I got a request to publish to open-vsx but I cannot since this extension would need to be published first.

If you could, it would be great to publish to [open-vsx](https://open-vsx.org/) but if you can't or don't want to, could I publish a version of this myself and give credit?

**Comment by psybers** [comment]
This is a duplicate of #140.

**Comment by be5invis** [comment]
Dupe.

**Comment by BrandonKirbyson** [comment]
Ok sorry figured it was worth a try to get your attention to this issue again. I love this extension but I will probably just get open-vsx people to use another injection extension.
