### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by joenil** [be5invis/vscode-custom-css#2]
![image](https://cloud.githubusercontent.com/assets/11400674/17222851/c03bede8-552c-11e6-9cc1-2e8d08460205.png)
It's so weird that the same config in my company computer works well, but something wrong with my mackbook, it seems the file specify in the setting `"vscode_custom_css.imports"` not work, I am sure that the version of vscode and extension in two computer is alike and enable extension already.

**Comment by be5invis** [comment]
@joenil The latest vscode-custom-css uses URL instead of file path.
You should write like this:

```
"vscode_custom_css.imports": [
	"file:///Users/yourname/Desktop/vscode-style.css"
]
```
