### ISSUE TITLE
Discussion about incorporating into VSCode core

### ISSUE THREAD

**Issue by damassi** [be5invis/vscode-custom-css#20]
This plugin is excellent -- the reason I made the switch over from Atom! Thank you. I'm wondering, has there been any discussion in the main VSCode repo about incorporating this functionality into the core? It seems like a logical feature. Any links to any discussions that you know about?

**Comment by wesbos** [comment]
I asked about this and it's apparently not going to happen because of perf issues it would cause

https://twitter.com/code/status/908081590076502016
