### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by duckfromdiscord** [be5invis/vscode-custom-css#202]
My `.vscode/settings.json`:
```json
{
    "vscode_custom_css.imports": [
      "file:///C:/Users/<my user name>/test.js"
      ],
    "vscode_custom_css.policy": true,
  }
```

`test.js`:
```js
console.log("Hello world");
```

Console output in developer tools:
![image](https://github.com/be5invis/vscode-custom-css/assets/113956421/c6eea1a1-966e-4060-9fe9-4a627b9a50c0)

Custom CSS & JS is loaded but nothing happens.

**Comment by tgienger** [comment]
did you fix it? if so how?

**Comment by duckfromdiscord** [comment]
Can't quite remember. I think I installed it wrong. What's the issue on your end?
