### ISSUE TITLE
Support for VSCode's Floating editor windows customization

### ISSUE THREAD

**Issue by PraneshBalasubramaniam** [be5invis/vscode-custom-css#206]
Hi, the changes done using the extension only applies to the main windows but not to the floating window (VSCode's new feature).
The [floating windows](https://code.visualstudio.com/updates/v1_85#_floating-editor-windows) created from the main window does not have the applied feature.
Can we make it to have same changes from main windows applied to the floating window or have separate option for floating window to apply CSS.

**Comment by RichardLuo0** [comment]
a workaround (you can remove css from "vscode_custom_css.imports"):
```js
import sheet from "./something.css" assert { type: "css" };

document.adoptedStyleSheets.push(sheet);
const oldOpen = window.open;
window.open = () => {
   const newWindow = oldOpen(...arguments);
   const document = newWindow.document;
   const newSheet = new newWindow.CSSStyleSheet();
   for (let i = 0; i < sheet.cssRules.length; i++) {
     newSheet.insertRule(sheet.cssRules[i].cssText);
   }
   document.adoptedStyleSheets.push(newSheet);
   return newWindow;
}
```
