### ISSUE TITLE
Failing to read the folder of vscode.app when reloading custom css

### ISSUE THREAD

**Issue by wout-junius** [be5invis/vscode-custom-css#209]
When reloading the custom css I get this error:

```
A system error occurred (EROFS: read-only file system, open '/private/var/folders/rl/_x93fp2d35z3x_bgcc9d3kh40000gn/T/AppTranslocation/F50F836D-FE0A-4356-9604-C8FD30372336/d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.c6d86701-7e6b-4135-ae84-276d34565540.bak-custom-css')
```

I have no clue what to do now

**Comment by maxpatiiuk** [comment]
Same issue. (on macOS in my case)
Started right after updating to the latest VS Code

Error:
> A system error occurred (EACCES: permission denied, open '/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.6564c76d-db71-4a9a-8710-be888d8e9aeb.bak-custom-css')

The file in question does not exist on the disk.
Reloading VS Code, reinstalling the extension, etc didn't help

**Comment by be5invis** [comment]
The extension needs write permission to write the CSS and create backups, so you may need to adjust your permissions.
If VSCode is installed in an RO FS then this extension cannot work.

**Comment by maxpatiiuk** [comment]
Thanks. I followed the instructions in this [README.md](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension#:~:text=in%20Administrator%20mode.-,Mac%20and%20Linux%20Users,-To%20ensure%20the) and the issue was resolved

Not sure why this started happening after a vscode update though
