### ISSUE TITLE
Can't get this running on Linux

### ISSUE THREAD

**Issue by iamsolankiamit** [be5invis/vscode-custom-css#21]
The file isn't loading.

The file is at the correct location. In dev tools it does show that the plugin has loaded. But custom.css file is not loaded.
vscode settings

```json
{
  "vscode_custom_css.imports": ["file:///home/fash/.vscode/custom.css"]
}
```

The file does exist at the said location. But it is not loaded into the module.

Any suggestions on how to get this running?

**Comment by iamsolankiamit** [comment]
Got it Working.
- First reinstalled the plugin
- Disable Custom Css
- Restart VsCode
- Enable Custom Css

:tada:  Works

**Comment by Shinkei** [comment]
This is not working for me, and now I get a message that says that my vscode is corrupted 😟

**Comment by be5invis** [comment]
@Shinkei 
**JUST IGNORE IT**.
This plugin alters Code itself, so it **will** say that it is corrupted.
