### ISSUE TITLE
Enable/Reload Custom CSS and JS Fatal Error EPERM: operation not permitted

### ISSUE THREAD

**Issue by FlowerCA77** [be5invis/vscode-custom-css#210]
When I try to _Enable/Reload Custom CSS and JS_ after vscode updated, it cannot work with a fatal error:

`Error: EPERM: operation not permitted, open 'c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-sandbox\workbench\workbench.93e48ee3-e81c-4750-9e98-220d9dfb096c.bak-custom-css' extension.updateCustomCSS {"value":"be5invis.vscode-custom-css","_lower":"be5invis.vscode-custom-css"}`

I do not know what the file `workbench.********-****-****-****-************.bak-custom-css` (those star are random value) is and I don't write the file in user settings.json file. I only write one custom css file in settings.json by `vscode_custom_css.imports` and this file is outside with vscode's directory, so vscode's update can not effect my css file and I checked my file is still existed after updated. 

<img width="1231" alt="Snipaste_2024-05-12_21-47-56" src="https://github.com/be5invis/vscode-custom-css/assets/82761452/d81b8f33-ac24-4787-909e-7317f350cc50">
<img width="435" alt="Snipaste_2024-05-12_21-48-32" src="https://github.com/be5invis/vscode-custom-css/assets/82761452/abf920c6-8818-43cc-8f60-d60f1efa7346">
<img width="333" alt="Snipaste_2024-05-12_21-48-42" src="https://github.com/be5invis/vscode-custom-css/assets/82761452/0f08d1ec-30e7-4fd1-9de3-ed088a1292d3">

_I'm sure I open vscode with administrator privileges_

Let me know if you need anymore information

Thanks for everyone who can help me.

**Comment by IOLOII** [comment]
Try & Flow this [readme](https://marketplace.visualstudio.com/items?itemName=drcika.apc-extension#:~:text=in%20Administrator%20mode.-,Mac%20and%20Linux%20Users,-To%20ensure%20the)

<img width="800" alt="image" src="https://github.com/be5invis/vscode-custom-css/assets/34856171/2a397f87-6d37-43d2-b7dd-4f3df466818e">

Here is after success setting :
<img width="551" alt="image" src="https://github.com/be5invis/vscode-custom-css/assets/34856171/e9c851fc-faf7-43bc-8562-3c6932d7e896">

**Comment by FlowerCA77** [comment]
thank you

**Comment by FlowerCA77** [comment]
thank you
