### ISSUE TITLE
EROFS Error when try enable plugin on flatpak

### ISSUE THREAD

**Issue by yhojann-cl** [be5invis/vscode-custom-css#214]
I use GNU/Linux (Ubuntu 24.04) and i have installed visual studio code from flatpak, i made my custom css located in

- `file:///home/user/.var/app/com.visualstudio.code/config/Code/User/custom.css`.

But says an error:

![Screenshot from 2024-07-11 14-31-08](https://github.com/be5invis/vscode-custom-css/assets/2144779/1138685f-5995-4f5c-ab76-ec3249c1ebba)

**Comment by be5invis** [comment]
This plugin will need to modify _VSCode itself_, so if you are readonly mounted VSCode then it will fail.

**Comment by Suraj9505** [comment]
i am facing the same issue can anyone guide me how to resolve it. I followed the commands given in documentation but am still unable to enable the css and js loader

**Comment by IronicDeGawd** [comment]
So if you have vscode installed with snap or flatpak, this wont work?
Have changed the permissions with sudo chown but still getting the above mentioned error!

**Comment by arigit** [comment]
+1, @be5invis  is it possible to reopen this
Can a permission be provided to the flatpak to allow this extension to modify the install?
