### ISSUE TITLE
Custom CSS and JS Loader not working in vscode v1.92

### ISSUE THREAD

**Issue by yashkhatri-minddeft** [be5invis/vscode-custom-css#216]
The plugin was working fine until I updated my vscode to version 1.92. Now any of my custom CSS or JS are not being applied.

**Comment by yashkhatri-minddeft** [comment]
I have done everything, re-enable plugin, re-installed plugin. But still it's not working. Seeking for help.

**Comment by be5invis** [comment]
Are there error messages shown in the console (Help → Toggle Developer Tools)?

**Comment by be5invis** [comment]
When I was testing locally it works completely fine. You need administrator / root permission when enabling custom CSS and JS, because this plugin need to **MODIFY VSCODE ITSELF**. Also if Code is installed in a read-only volume, it will also fail.

**Comment by yashkhatri-minddeft** [comment]
> Are there error messages shown in the console (Help → Toggle Developer Tools)?
There is only one error in console which is "View has not been initialized after retrying for 5 seconds.".

**Comment by yashkhatri-minddeft** [comment]
> When I was testing locally it works completely fine. You need administrator / root permission when enabling custom CSS and JS, because this plugin need to **MODIFY VSCODE ITSELF**. Also if Code is installed in a read-only volume, it will also fail.

I have given the permissions of root to vscode already. Do I have to give that again?

**Comment by be5invis** [comment]
You need to run VSCode in admin/elevated/root permission and run "enable custom CSS/JS", so it get the ability to modify itself.

**Comment by yashkhatri-minddeft** [comment]
I changed permission of code directory which is located in /use/share/code, to Create and delete files in root group, and it worked fine.
Thanks for the help @be5invis.

**Comment by dongkyun-dev** [comment]
@be5invis @yashkhatri-minddeft 
How it works????
Custom CSS and JS Loader not works in vscode@1.92.
The plugin was working fine until update to 1.92

**Comment by dongkyun-dev** [comment]
![CleanShot 2024-08-19 at 11 44 18@2x](https://github.com/user-attachments/assets/5fbec390-516e-4f01-82cb-356fc5f16c53)

log is here
