### ISSUE TITLE
Can't get it to work at all

### ISSUE THREAD

**Issue by narcolepticinsomniac** [be5invis/vscode-custom-css#22]
Trying to load a local custom.css file and it either fails to load or says it's loaded, but no CSS is applied. I'm looking through closed issues, and the answers are all over the place. I'm trying all of them, and nothing works.

>Items in “`vscode_custom_css.imports`” should be URLs, instead of file paths. For local files, prefix it with “`file://`”.

should be:

`"vscode_custom_css.imports": "file:///C:/Users/D/custom.css"`

no?

I can Ctrl + Click the link and it opens. It says it loads. I'm loading it with admin privileges. No CSS is applied. 

One user refers to `"vscode_custom_css.file"` https://github.com/be5invis/vscode-custom-css/issues/1#issue-164908187, which I see nothing about, but I also tried every variation of that. Nothing. I don't get what I'm doing wrong here.

**Comment by ArturoDent** [comment]
It's an array so you need the brackets :

"vscode_custom_css.imports": [ "file:///C:/Users/D/custom.css" ]

`Then F1 and "Reload Custom CSS and JS"
The I might have had to do F1 and "Enable Custom CSS and JS" as well.

Their documentation is awful.

**Comment by narcolepticinsomniac** [comment]
>Their documentation is awful.

No kidding. @ArturoDent Much appreciated!
