### ISSUE TITLE
Custom CSS and JS Loader Not Working

### ISSUE THREAD

**Issue by rupnil-codes** [be5invis/vscode-custom-css#220]
![image](https://github.com/user-attachments/assets/8abb08ed-de36-49de-8244-a92977b1b31c)
I initialized the things, and also enabled them. Still not working

**Comment by rupnil-codes** [comment]
At first it was working fine then idk what happened and it just wont work

**Comment by halowahyudi** [comment]
this issue after vscode update.

**Comment by rupnil-codes** [comment]
I did, but still not workin :/

**Comment by ElBaraaRadwan** [comment]
hi @rupnil-codes 
I have the same issue that you have, please tag me if you fix it.

**Comment by rupnil-codes** [comment]
@ElBaraaRadwan lmao i forgot about this, i switched to pycharm :/

**Comment by be5invis** [comment]
Are there error logs in VSCode's developer view?

**Comment by ElBaraaRadwan** [comment]
@rupnil-codes xD
No problem, i already forgot about it.
