### ISSUE TITLE
No way to work in VS Code server or code-server?

### ISSUE THREAD

**Issue by bilogic** [be5invis/vscode-custom-css#221]
I primarily use code-server and https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons does not report a problem

However, this does

![image](https://github.com/user-attachments/assets/ba007968-5eb0-446b-a859-2da2ab47aad3)

**Comment by be5invis** [comment]
I have no idea. It is intended to be ran at client side, once after each VSCode update only to apply the custom CSS/JS.

**Comment by bilogic** [comment]
I think there is a way to define where an extension can/cannot run
