### ISSUE TITLE
Custom CSS and JS Loader not works in vscode@1.92.2

### ISSUE THREAD

**Issue by dongkyun-dev** [be5invis/vscode-custom-css#222]
This works well until update vscode to 1.92.2
I also run a command `sudo chown -R $(whoami) "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"`.
But It still doesm't work. How do I fix it?

**Comment by be5invis** [comment]
No repro on my system. Have you modified the permission so that **vscode could modify itself**?

**Comment by dannypernik** [comment]
I haven't gotten it to work yet but needed to escape the spaces like so to get the command to run without an error:
`sudo chown -R $(whoami) /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron`

**Comment by joseavr** [comment]
I also have the same issue. :(

**Comment by yannis-iG** [comment]
Same issue on Vscode 1.92.2
<img width="463" alt="Screenshot 2024-08-27 at 14 49 49" src="https://github.com/user-attachments/assets/fdc8e0be-73cf-43cd-929b-87a267c47bd2">

**Comment by dongkyun-dev** [comment]
@be5invis 
I modified permission of vscode by your guide. But It didn't work.
I found only solution is change extension to Apc Customize UI++.
