### ISSUE TITLE
settings.json is not valid

### ISSUE THREAD

**Issue by AlexMa2011** [be5invis/vscode-custom-css#224]
When I finished editing the `settings.json`, the editor notified me that there were errors in `settings.json`, but actually, it was correct. The custom CSS could also work properly as expected.

```json
{
    "vscode_custom_css.imports": ["https://gist.githubusercontent.com/Ynng/3275eb9cb2b5816554877e5518417f44/raw/1447d34712a59a1ac48ae1ce6da18c5460ea7cea/custom.css"]
}
```
<img width="1283" alt="截屏2024-08-25 17 50 14" src="https://github.com/user-attachments/assets/dfc8f7b4-00b3-4efc-8f7e-f57a7285cbe1">
<img width="461" alt="截屏2024-08-25 17 50 37" src="https://github.com/user-attachments/assets/4e164c8c-6882-4e11-9350-c3bed023babc">

**Comment by joseavr** [comment]
this is a syntax error. you are missing a comma at the end of the line 16.
