### ISSUE TITLE
command 'extension.updateCustomCSS' not found in VSCode 1.94

### ISSUE THREAD

**Issue by nickmcummins** [be5invis/vscode-custom-css#227]
I have been using this extension for a while. Suddenly though, after updating to the latest version of VSCode (Preview) I am getting an error when attempting to run any of the extension commands. 

I was able to reproduce the issue on two separate machines.
  
![image](https://github.com/user-attachments/assets/6f1639bd-d8be-4710-9330-663ad75ed0ce)

![image](https://github.com/user-attachments/assets/c7c065bc-b38e-43b1-9797-593c289901a8)

**Comment by lakshits11** [comment]
Same

**Comment by be5invis** [comment]
Are there logs in VSCode's dev console?

**Comment by nickmcummins** [comment]
> Are there logs in VSCode's dev console?

Yes.
> workbench.desktop.main.js:222673 Activating extension 'be5invis.vscode-custom-css' failed: Cannot read properties of undefined (reading 'filename').
$onExtensionActivationError	@	workbench.desktop.main.js:222673

**Comment by be5invis** [comment]
Fixed in last version. Resolve.
