### ISSUE TITLE
Is it possible to use remote files?

### ISSUE THREAD

**Issue by wesbos** [be5invis/vscode-custom-css#23]
I'd like to link to a github file so it's automatically updated but it throws a content security policy error. Any way around this?

**Comment by blacktop** [comment]
https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_using-a-content-security-policy

Maybe add `https:` to `style-src`

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' https: data:; media-src 'none'; child-src 'self'; object-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https:; font-src 'self' https:;">
```

It defaults to only allowing things to loaded locally.

You could also generate a `nonce` at runtime to keep vscode as secure as possible.

**Comment by blacktop** [comment]
you could also grab the file and put is somewhere local.

**Comment by be5invis** [comment]
@wesbos I think you should contact Code team to remove the CSP filter.
Closed.
