### ISSUE TITLE
Problem or reloading the extension each time

### ISSUE THREAD

**Issue by itzzzme** [be5invis/vscode-custom-css#239]
Hey I was curious to know if there is any workaround to auto reload the extension on each start of vs code (Note: I don't launch vs code as admin) i want to find the way where I can do it without admin permission just by auto reloading it on each launch of code

**Comment by barta-gergo** [comment]
> Hey I was curious to know if there is any workaround to auto reload the extension on each start of vs code (Note: I don't launch vs code as admin) i want to find the way where I can do it without admin permission just by auto reloading it on each launch of code

I managed to create a workaround. https://github.com/BartaG512/custom-css-hot-reload/
The idea was to inject a JS file by the extension which is monitoring the vscode DOM with a Mutation Observer.
The extension sending message through setting a Status Bar Item's tooltip text when the import files changed. 
Very hacky but it works.

For CSS it is great, for JS not really.

**Comment by BartaG512** [comment]
I've managed to create a workaround. https://github.com/BartaG512/custom-css-hot-reload/
The idea was to inject a JS file by the extension which is monitoring the vscode DOM with a Mutation Observer.
The extension sending message through setting a Status Bar Item's tooltip text when the import files changed.
Very hacky but it works.

For CSS it is great, for JS not really.

This was you need to enable and reload it once after install
