### ISSUE TITLE
Stopped working v 1.17

### ISSUE THREAD

**Issue by mattJamesMedia** [be5invis/vscode-custom-css#24]
When VS Code updated to 1.17, custom styles disappeared.

**Comment by be5invis** [comment]
What are your styles? Does the loaded icon show up in the status bar?

发自我的 iPhone

在 2017年10月22日，22:12，Matt James <notifications@github.com<mailto:notifications@github.com>> 写道：


When VS Code updated to 1.17, custom styles disappeared.

**Comment by be5invis** [comment]
Please note that Code may change its internal DOM structure after update. To identify whether the style is loaded please find the "bucket" icon on the status bar.

**Comment by mattJamesMedia** [comment]
Thanks, it's now fixed with 1.17.2.
