### ISSUE TITLE
Styles disabled after enabling or reloading from VSCode v1.96.0

### ISSUE THREAD

**Issue by CarlosLopezElorduy** [be5invis/vscode-custom-css#247]
I recently upgraded VSCode to version 1.96.0. Previously, the extension was working wonderfully. However, after the upgrade, I attepted to enable the extension again (`Enable Custom CSS and JS` command) and after the typical pop up where it tells you to restart VSCode, it comes followed by the pop-up saying that the styles have been disabled (same behaviour as using the command `Disable Custom CSS and JS`).

Therefore, the styles never get activated, as when I enable them, they get dissabled immediately. The same happens with the `Disable Custom CSS and JS` command.

![image](https://github.com/user-attachments/assets/13abe04a-d3b0-4553-aab6-59d316979182)

> [!NOTE]
> Using Ubuntu 24.10
> I already changed the permissions of the `code` executable with `sudo chown -R $(whoami) /usr/bin/code`

**Comment by adirizq** [comment]
I encountered the same issue but managed to resolve it. The following steps fixed the problem for me:
1. Close all running VSCode instances
2. Execute `sudo chown -R $(whoami) "$(which code)"` and `sudo chown -R $(whoami) /usr/share/code`
3. Restart all terminal (I don't know whether this do anything)
4. Relaunch VSCode using `code`

My environment:
Ubuntu 24.04.1 LTS
VSCode 1.96.0

**Comment by CarlosLopezElorduy** [comment]
Thanks a lot @adirizq , I confirm this solved it for me aswell!
