### ISSUE TITLE
Stopped working after update to Code Version 1.19.1 on Mac OS

### ISSUE THREAD

**Issue by jordanboston** [be5invis/vscode-custom-css#26]
Not sure if this is just me and some other issue, but thought I should post this to see if anyone else has experienced any issues with the styles all of a sudden not showing up after updating VSCode.

**Comment by BenGedi** [comment]
Not working also on windows after update to 1.19.1

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/34287123-193be926-e720-11e7-9fbd-480b52a4c664.png)
The loader is OK. Maybe something related to CSP.

**Comment by be5invis** [comment]
I do not have any issue loading CSSes.
What are your imports?

**Comment by be5invis** [comment]
@jordanboston @BenGedi  Please provide your list of imported CSSes.
**For changing style in the editor, please note that the class names may frequently change in each version of Code. Please update them after any Code update.**

**Comment by be5invis** [comment]
@jordanboston @BenGedi 
Also, **Every time Code updated you must re-enable the styles.**

**Comment by jordanboston** [comment]
`"vscode_custom_css.imports": ["file:///Users/user/vscode-styles/styles.css"]`

```.mtk14, .mtk8, .mtki {
  font-family: 'Script12 BT';
  font-size: 1.1em;
}
.mtk6 {
	font-family: 'Inconsolata';
	font-style: italic;
	font-size: 1.2em;
}
.type.storage.arrow.function {
	font-family: 'Fira Code'
}
```

*But that makes sense.*  How do we re-enable the styles?  
Sorry, I must have missed that or something.

We can just close this out then.  I'll find and update the css.  Do you remember where the css inspector is in Code?  I can't seem to find it now.   Thanks!

This has been a great asset in setting up the editor!

**Comment by jordanboston** [comment]
Oh, found that here and it is working now without needing to change the CSS.  Wonderful!
<img width="775" alt="screen shot 2017-12-21 at 10 21 23 pm" src="https://user-images.githubusercontent.com/1487071/34287684-b3a10092-e69d-11e7-970c-a394d0396e55.png">

Maybe a note should be made about that, regarding updates, in the readme.  If it is not already there and I just missed it.

**Comment by be5invis** [comment]
Added a note in in v2.6.0.

**Comment by BenGedi** [comment]
I've Enable Custom Css And JS (with administrator), my imported css file path is also fine.
I see the pluging icon logo, and I still don't the my css changes taking effect 😕
![image](https://user-images.githubusercontent.com/7399282/34288902-79803602-e6f8-11e7-84a6-6ecc40686336.png)

![image](https://user-images.githubusercontent.com/7399282/34289048-4ae57888-e6f9-11e7-9d9b-c0b526ae935c.png)

![image](https://user-images.githubusercontent.com/7399282/34289025-28e745c2-e6f9-11e7-8ad3-9874d3833c19.png)

**Comment by BenGedi** [comment]
Now for unknown reason, i suddenly don't see the Loader icon any more :(

**Comment by jordanboston** [comment]
@BenGedi Did you `Cmd, Shift, P` to enable it here yet?
<img width="414" alt="screen shot 2017-12-22 at 1 05 30 pm" src="https://user-images.githubusercontent.com/1487071/34312423-ec9f0d50-e718-11e7-8854-a88f116cee4a.png">
That is what worked for me.

**Comment by BenGedi** [comment]
@jordanboston yes of course... I've disabled and re-enable it again and the icon has returned, but still my css changes on "styles.css" is not working... :/

**Comment by be5invis** [comment]
@BenGedi Do you have any messages in the developer tool?
(You can open the dev tool and reload the window)

**Comment by BenGedi** [comment]
@be5invis  thanks! 
I see now that the "styles.css" is not reachable... 
But i don't understand why, because the path is fine!

![image](https://user-images.githubusercontent.com/7399282/34318902-7a0c118e-e7db-11e7-99d3-041b7e1ebc20.png)

**Comment by BenGedi** [comment]
@be5invis i don't think this is it

![image](https://user-images.githubusercontent.com/7399282/34319010-850b35ee-e7de-11e7-97a9-9e91afdc6c0d.png)

**Comment by be5invis** [comment]
@BenGedi Do you messed up casing?

**Comment by BenGedi** [comment]
@be5invis sorry, casting? what do you mean?

**Comment by be5invis** [comment]
@BenGedi `ABC` vs `abc`

**Comment by BenGedi** [comment]
I've changed to lowercase and still the get the error

**Comment by be5invis** [comment]
@BenGedi Chrome is case sensitive **even on Windows**, which means that you have to match your URL with the actual casing of your file path.

**Comment by BenGedi** [comment]
@be5invis it is the actual path :/

![image](https://user-images.githubusercontent.com/7399282/34319059-e1580146-e7df-11e7-9abe-53f679483497.png)

**Comment by be5invis** [comment]
@BenGedi Have you tried to un-hide the file?

**Comment by BenGedi** [comment]
![image](https://user-images.githubusercontent.com/7399282/34319071-6ad84d72-e7e0-11e7-9f5e-81dd41a545d3.png)

**Comment by be5invis** [comment]
@BenGedi 
That's strange. Maybe you can try to move the file to somewhere else.

**Comment by BenGedi** [comment]
Ok this is even stranger, i've moved it to c:, and still getting, same error: 

![image](https://user-images.githubusercontent.com/7399282/34319084-27ce5228-e7e1-11e7-925c-ae80ac8210d3.png)

**Comment by be5invis** [comment]
@BenGedi Every time you changed the imports option you need to disable and re-enable the plugin with `F1` menu.

**Comment by BenGedi** [comment]
AWESOME MAN!!!!!! IT IS WORKING!!!
Thanks very much for your help and patience 😁

**Comment by be5invis** [comment]
@BenGedi I've added more notes in README.
