### ISSUE TITLE
cscodestyles.css

### ISSUE THREAD

**Issue by Clickys** [be5invis/vscode-custom-css#27]
// you'll need to change this to an absolute path on your computer
  "vscode_custom_css.imports": [
    "/Users/clickys/.vscodestyles.css"
  ],

i have no idea what i have to fill here. Can someone please help me out ?

**Comment by be5invis** [comment]
It should be an URL, not a file path.

**Comment by Clickys** [comment]
a url of what ?

**Comment by be5invis** [comment]
Of your CSS. Use file://Users/clicys/whatever

**Comment by Clickys** [comment]
Iam really confused and sorry if my questions are stupid. Iam working on a local environment . I wanted to install the Cobalt2 theme and it suggest to donwload your plugin . I dont understand what is this url for and where it should point to ? Whats the reason of that url and where should i point it to ?

**Comment by be5invis** [comment]
Read this please: https://en.wikipedia.org/wiki/File_URI_scheme
A file URL to your CSS file should be put into your config. After that, Enable custom CSS with its command.

**Comment by be5invis** [comment]
For your case, the configuration should become

```
"vscode_custom_css.imports": [
"file:///Users/clickys/.vscodestyles.css"
]
```
if that CSS file is really at `/Users/clickys/.vscodestyles.css`

**Comment by be5invis** [comment]
Cobalt2's doc is WRONG. I've opened an issue to them.

**Comment by Clickys** [comment]
iam trying to locate where vscode styles are.

**Comment by be5invis** [comment]
You should CREATE a CSS file, copy some code from that theme, save, and enable it within Code.

**Comment by Altug** [comment]
Where do we write this code to run? Or do we?
I don't understand what to do .. really confusing..

**Comment by be5invis** [comment]
@Clickys @Altug 
Assume your home directory is `/Users/xxx`:

1. **CREATE** a file at `/Users/xxx/.vscodestyles.css`. Leave it empty.
2. Copy all data from [here](https://github.com/wesbos/cobalt2-vscode/blob/master/cobalt2-custom-hacks.css) into `/Users/xxx/.vscodestyles.css`. Save.
3. In your VSCode settings, write
    ```
    "vscode_custom_css.imports": [
        "file:///Users/xxx/.vscodestyles.css"
    ]
    ```
4. Run the "Enable Custom CSS/JS" in your command palette. Make sure you have the permission needed.
5. Restart Code and it would took effect.

**Comment by Altug** [comment]
Thank you @be5invis I think it is done and I now understand how it works.

Still I can only change fonts from user settings file, the .vscodestyle.css seems no effect even if I have properly set the location from the user settings file.

It is looking fine now and I'm using a free font: "Consolas" only. Couldn't mix 2 fonts to look like as wesbos show..

I'll look into this in another time :)

Thanks for helping me out.

/cheers
