### ISSUE TITLE
CSS file not connected

### ISSUE THREAD

**Issue by Waldemar-Dassler** [be5invis/vscode-custom-css#28]
Hi! My css file do not included what i do wrong? Maybe you have an error?
1. Create the file 
2. Enabled extension
3. Give permission for file
It`s not work fo me =(
![2018-01-19 21 14 03](https://user-images.githubusercontent.com/25832802/35167379-ff0215ea-fd5d-11e7-9ce0-760a7a75e522.png)

**Comment by be5invis** [comment]
There should be THREE slashes after “file:”, not TWO.

**Comment by be5invis** [comment]
Are modern programmers forgetting how to write a correct URL? What a regression!

**Comment by Waldemar-Dassler** [comment]
The first time I used 3 slashes! I now why dont work first time! For correct work First i am disable the extension and the enable and now its work

**Comment by Waldemar-Dassler** [comment]
some times need to disable extension

**Comment by be5invis** [comment]
There’s an indicator on the status bar to indicate whether the plugin is working. Every time you update the configuration you need to disable then re-enable the custom CSS. It’s already written in the README.
