### ISSUE TITLE
Hide tabs

### ISSUE THREAD

**Issue by Waldemar-Dassler** [be5invis/vscode-custom-css#29]
Hello!
When I hide the tabs then I have spaces in bottom =(
I use that for hiding tabs
```
.editor .content .container .title {
    display: none !important;
}
```
and my problem white spaces after hiding tabs
![2018-01-30 8 43 29](https://user-images.githubusercontent.com/25832802/35552032-bc5e6992-059a-11e8-9b2a-2fecc3e6d778.png)

**Comment by be5invis** [comment]
Maybe you need also to update the height of editing area.
Closed as external.

**Comment by be5invis** [comment]
Or maybe uses JavaScript to set the height of the editing control. In this case there's really no good solutions.

**Comment by Waldemar-Dassler** [comment]
Can you help me?

**Comment by be5invis** [comment]
Could you please explain:

> Doest work

WHAT does not work?

> Can you help me?

About what?

**Comment by Waldemar-Dassler** [comment]
i want change height code container I have i white spaces =(

**Comment by be5invis** [comment]
The plugin itself is working, however whether a CSS would work, especially styles about the metrics, depends on the internal logic of the Code.

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/35554215-da37aa60-05d5-11e8-81b0-e343d8ce3980.png)
The element's height is set by JavaScript. You cannot do anything on it via CSS.
Using custom JS may work, but it is very risky.

**Comment by Waldemar-Dassler** [comment]
I dont now js

**Comment by be5invis** [comment]
Then you cannot control it. The layout and size of each element is completely controlled by JS.
Sorry I cannot provide any help on this. Maybe you could open an issue/feature request in the Code repository.

**Comment by Waldemar-Dassler** [comment]
ok! thnx
