### ISSUE TITLE
Not working in VScode 1.20.0

### ISSUE THREAD

**Issue by NicolaSansom** [be5invis/vscode-custom-css#32]
I have just updated to the new version of VScode since then my custom css does not seem to be loading in. I have tried running `Reload Custom CSS and JS` serval times with no luck.

Any idea whats going on?

**Comment by be5invis** [comment]
Also your OS? Are you running with the proper permission?

**Comment by NicolaSansom** [comment]
I can see the little icon and I have windows 7 and I have admin rights.

**Comment by be5invis** [comment]
Then maybe the URL you filled is incorrect, or the HTML elements that you are styling changed in v1.20.0.

**Comment by NicolaSansom** [comment]
I have just checked and the html elements I am targetting in css have not changed in chrome dev tools. It is  just that css in not being applied. What do you mean by url the file passed within settings?

**Comment by be5invis** [comment]
Perhaps. In the settings it should always be a **URL** not a **file path**. If the CSS is on your local disk you need to convert it into a `file://` URL.

**Comment by NicolaSansom** [comment]
It was the url that was incorrect my bad! Thanks for helping with this just sorry.

**Comment by muloka** [comment]
Thanks I was also having trouble with this. A configuration setting must of changed in VS Code where it made the presence of `file://` more strict / expected.
