### ISSUE TITLE
Custom CSS not working properly in VSCode 1.20.1

### ISSUE THREAD

**Issue by jobarbo** [be5invis/vscode-custom-css#33]
Since the lates patch, my custom styles is not working. I tried to reload, or even uninstall and reinstall but nothing seems to do the trick. I thought it would be a good idea to let you know.

**Comment by be5invis** [comment]
What's your config? Is there a little bucket on the status bar?
Please make sure that every load URLs are really... URL.

**Comment by jobarbo** [comment]
it seems that before it was working with this: '' /Volumes/Macintosh HD/Users/<myuser>/.vscodestyles.css " but now it's only working with '' file:///Volumes/Macintosh HD/Users/<myuser>/.vscodestyles.css '' 

You can close the issue, thanks for the quick reply. Have a great day!

**Comment by be5invis** [comment]
The instruction that the configuration should be URL has been there for decades...
Closed.
