### ISSUE TITLE
Not working with 1.21 insiders

### ISSUE THREAD

**Issue by PGDJ** [be5invis/vscode-custom-css#35]
It was working before for me but now I am not seeing the logo for the extension in the bar

my config is the same and my file shows up when I alt+click on it. 

it is currently `"vscode_custom_css.imports": ["file:///Users/myUsername/.vscodestyles.css"],`

**Comment by be5invis** [comment]
Is the URL really right? If you are on Windows the C:/ part is not omitable.
I do not have insider build...

发自我的 iPhone

在 2018年2月24日，04:18，Andrew Stobie <notifications@github.com<mailto:notifications@github.com>> 写道：


It was working before for me but now I am not seeing the logo for the extension in the bar

my config is the same and my file shows up when I alt+click on it.

it is currently "vscode_custom_css.imports": ["file:///Users/myUsername/.vscodestyles.css"],`

**Comment by PGDJ** [comment]
I am running it on Mac OS high sierra and I am getting

`ERR EROFS: read-only file system, open '/private/var/folders/8f/.../T/AppTranslocation/.../d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss': Error: EROFS: read-only file system, open '/private/var/folders/8f/.../T/AppTranslocation/.../d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss'`

as an error.

I am also running it as an administrator.

**Comment by be5invis** [comment]
What are the permissions of these files? Code may changed them.

发自我的 iPhone

在 2018年2月24日，04:39，Andrew Stobie <notifications@github.com<mailto:notifications@github.com>> 写道：


I am running it on Mac OS high sierra and I am getting

ERR EROFS: read-only file system, open '/private/var/folders/8f/.../T/AppTranslocation/.../d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss': Error: EROFS: read-only file system, open '/private/var/folders/8f/.../T/AppTranslocation/.../d/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.bak-customcss'

as an error.

I am also running it as an administrator.

**Comment by PGDJ** [comment]
Tried it in 1.20.1 (regular build) and it still works there. I don't know if you want to leave this open for when 1.21 comes around or close it and have it re-opened then, but either way just giving you a heads up.

**Comment by PGDJ** [comment]
The whole thing seems to be read only file system even when I sudo try to change permissions it is coughing up an error. I am continuing to poke around but I don't claim to know enough about this to really know what is going on.

**Comment by PGDJ** [comment]
Nevermind! I found the solution. It was the dumbest issue. /private/var was because I never moved VS-Code insiders from my Downloads folder.  brilliant.

**Comment by scottsf** [comment]
I'm also running into the same issue. Only difference is I moved my VS-Code from my Downloads directory to /Users/Applications. Am I missing something else? 

<img width="795" alt="Developer Tools - file::::private:var:folders:yr:drqp0ctx0g39x0_dmhr53tnr0000gn:T:AppTranslocation:9A8B2F1B-D96E-4C8F-AFDD-406A… 2019-07-11 03-37-42" src="https://user-images.githubusercontent.com/43653189/61045537-e50d0f80-a38f-11e9-9564-3e0a8a75f836.png">

**Comment by ICeZer0** [comment]
@scottsf on MacOS make sure to force close and restart VSCode
