### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by rockmandash** [be5invis/vscode-custom-css#36]
with latest code, this feature seems not working anymore

**Comment by be5invis** [comment]
Please double-check the **correctness** of the URLs in your configuration. It should be a **URL**, **NOT** a file path, and the disk letter part (`C:/`) is not omittable if you are on Windows.

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36660752-3c029c5c-1b14-11e8-9bfe-e21823ec0cbd.png)
Yes, I'm using surge to host my settings

**Comment by be5invis** [comment]
Could you please try to download it to localhost?
The support of remote resource is added by @Kasperfred.

**Comment by rockmandash** [comment]
Not working, ><""

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36666431-9a405e7e-1b25-11e8-8bac-635fa83f60fb.png)
Not working 😥😥😥😥

**Comment by be5invis** [comment]
Could you please to escape that space? Do not forget to reload the CSS after the config is changed.

发自我的 iPhone

在 2018年2月26日，18:48，Joseph Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7580792%2F36666431-9a405e7e-1b25-11e8-8bac-635fa83f60fb.png&data=02%7C01%7C%7Ca2c3ec6e85f34639a79d08d57d067ffc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636552389222394893&sdata=56DVrJnthPd8OocYEDp2IZjaoWIHgKKH3yKPkLp46xI%3D&reserved=0>
Not working 😥😥😥😥

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36667947-a951d91a-1b2a-11e8-82fa-d441c34c24b2.png)
Can't escape white space in json

**Comment by be5invis** [comment]
I mean, URL escape. Space should be escaped as a plus symbol.

发自我的 iPhone

在 2018年2月26日，19:25，Joseph Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7580792%2F36667947-a951d91a-1b2a-11e8-82fa-d441c34c24b2.png&data=02%7C01%7C%7C3388356ce14244c9ac1208d57d0b935d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636552411027166304&sdata=eInyGJh9HMMrWmV9EKlMbUCVSzwnp%2BTjEUNW14Sd7Ck%3D&reserved=0>
Can't escape white space in json

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36669530-2ac723ec-1b30-11e8-8c32-6da8f990dee4.png)
Not working too.😰😰😰😰

**Comment by Kasperfred** [comment]
Hmm. 

The remote download ignores anything that doesn't start with http or https - Did you remember to start vscode in administrator mode?

Also, you will have to use the reload css command after each update. 

Finally, could you open developer tools in vscode (found under the help menu), and check the console for any errors, and if there's a `content-policy` meta tag in the head, along with whether your css is in a `style` tag in the body section?

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36678783-9c6d5072-1b4c-11e8-9df2-82be32b9593e.png)
![image](https://user-images.githubusercontent.com/7580792/36678868-d2a46108-1b4c-11e8-9c62-b10048cc825b.png)

OK, I forgot there is a developer tool out there XD
It's really convenient.
So I manually add style into style tag, it works, but the plugin still don't

**Comment by rockmandash** [comment]
![image](https://user-images.githubusercontent.com/7580792/36678982-13c121d0-1b4d-11e8-8984-649a5babef05.png)
This is not the URL I described in my settings.

**Comment by be5invis** [comment]
The message said that the plugin IS running. Did you see the little bucket icon on the status bar after you execute the enable/reload CSS command?

发自我的 iPhone

在 2018年2月26日，23:29，Joseph Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7580792%2F36678783-9c6d5072-1b4c-11e8-9df2-82be32b9593e.png&data=02%7C01%7C%7C2c04970e6ac84d14ed0508d57d2db22c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636552557567104650&sdata=QFuLoVuLOkp%2FOJ1kvxJ%2BErD8HB9F%2Ft069BEEAB4u%2Bxk%3D&reserved=0>
[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F7580792%2F36678868-d2a46108-1b4c-11e8-9c62-b10048cc825b.png&data=02%7C01%7C%7C2c04970e6ac84d14ed0508d57d2db22c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636552557567104650&sdata=C3db2lBU6v4Fv%2BKBBe6%2BPtHXEYseZJIU0J02Gnrodj0%3D&reserved=0>

OK, I forgot there is a developer tool out there XD
It's really convenient.
So I manually add style into style tag, it works, but the plugin still don't

**Comment by be5invis** [comment]
This is the status bar icon. The plugin is running. Please MAKE SURE that you run the re-enable Custom CSS command every time after you changed the configuration.

**Comment by be5invis** [comment]
Also you need THREE slashes after the “file:”.

**Comment by Kasperfred** [comment]
If the same appears appears when using a http(s) url, and you've made sure that the setting `vscode_custom_css.policy` is set to true, it would appear from the screenshots that you're using an outdated version of the plugin. Specifically, one that hasn't gotten the #31 pr. yet.

**Comment by rockmandash** [comment]
THREE slashes seem fine.

**Comment by claide** [comment]
Hi, had a trouble loading my custom css.

**Below is my current version of Code**

> Version: 1.36.1 (user setup)
> Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
> Date: 2019-07-08T22:59:35.033Z
> Electron: 4.2.5
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

**settings.json**
```
"vscode_custom_css.imports": ["file:///C:/Users/magal/vscodecustom.css"],
"vscode_custom_css.policy": true
```
**relative path of custom css**

> C:\Users\magal\vscodecustom.css

Tried disabling and enabling the extension but no luck.

**Comment by claide** [comment]
Oh snap! Just got it working by manually enabling the extension by

> CTRL + SHIFT + P and then type "Enable Custom CSS and JS"

Thanks!

**Comment by oarkflow** [comment]
I've tried everything but still not able to make it work.

```json
  "vscode_custom_css.imports": [
    "file:///home/sujit/.vscode/custom-vscode.css",
    "file:///home/sujit/.vscode/custom-vscode.js"
  ],
    "vscode_custom_css.policy": true,
```

> `CTRL + SHIFT + P -> Enable Custom CSS and JS` => No Luck
> File Paths are fine and files have same whomi as current user
