### ISSUE TITLE
How to change underline style from dash to solid for errors etc...

### ISSUE THREAD

**Issue by laksh1010** [be5invis/vscode-custom-css#38]
So far i could change the colors as follows in settings 

```
"workbench.colorCustomizations": {
        "editor.rangeHighlightBackground": "#8E1212",
        "editorWarning.foreground": "#ff0",
        "editorInfo.foreground": "#ff00dd",
        "editorError.foreground": "#ff1b01"
    },
```

But still i could not change the **font decoration style** such as underline style etc. by default its kinda wavy or dash. i need it solid and also color has to be dynamic according to above settings or what ever theme specific color settings for different scenarios such as error , info, warnings etc.

![image](https://user-images.githubusercontent.com/34805854/37562689-bbd499fa-2a94-11e8-9162-7bbae2b73321.png)

 i already installed [vscode custom css](https://github.com/be5invis/vscode-custom-css) also but couldn't figure it out yet. i currently use **cobalt 2** theme. 

I have linked and tried some code here n there but not wokring still. here is my custom.css and i think its linked correctly as when i navigate i open the correct file.

in user settings : 
```
 "vscode_custom_css.imports": [
        "file:///Users/LJ/LJStuff/Work/dev/easybooking/ebmapp/.vscode/custom.css"
    ],
```
custom.css: (i think i did not get the correct way still. i used this code from some other stackoverflow. still figuring out how to do my own customization as i need)

```
.monaco-editor.vs-dark .greensquiggly,
.monaco-editor.vs .greensquiggly {
  /* yellow squiggly */
  background: url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' height='3' width='6'><g fill='#FF0'><path d='M5.5 0l-3 3H1.1l3-3z'/><path d='M4 0l2 2V.6L5.4 0zM0 2l1 1h1.4L0 .6z'/></g></svg>")
    repeat-x 0 100%;

  /* rectangle */
  background: none;
  border: 1px solid yellow;

  /* underline */
  background:none;
  border-bottom: 1px solid yellow; /* i need underline color be dynamic for error ,warning , infor etc */
}
```

**Comment by lolmaus** [comment]
The error underlining is not a font-decoration of code text nodes. The underlining consists of absolutely positioned elements.

Here's how you can target it.

1. Open the Chrome developer console in Code.
2. Zoom in on the code with the error as much as you can.
3. Enable the select element mode ![image](https://user-images.githubusercontent.com/200884/37765477-437e4de0-2dd5-11e8-82ce-1fb9cc5e7b35.png) and try to select the squiggly line. Another element will be selected instead.
4. In the DOM tree, find the nearest parent of the selected element that occupies the whole edtior area. It should have an HTML class of `view-lines`.
5. Now try selecting the squiggly line again. It will work now.

You can now inspect the HTML classes on the squiggly line element and the styles that make it squiggly. Spoiler: it's a background image.

**Comment by rohan07** [comment]
It still doesn't work for me. If anyone figured it out, can you please post your solution?

**Comment by rohan07** [comment]
@lolmaus - Here is what I have:
`  .monaco-editor.vs .squiggly-d-error,
	.monaco-editor.vs-dark .squiggly-d-error {
		background: transparent;
		border-bottom: 0px double #E47777;
	}
	.monaco-editor.vs .squiggly-c-warning,
	.monaco-editor.vs-dark .squiggly-c-warning {
		border-bottom: 0px double #71B771;
	}
	.monaco-editor.vs .squiggly-b-info,
	.monaco-editor.vs-dark .squiggly-b-info {
		border-bottom: 0px double #71B771;
	}
	.monaco-editor.vs .squiggly-a-hint,
	.monaco-editor.vs-dark .squiggly-a-hint {
		border-bottom: 0px double #6c6c6c;
	}
`

**Comment by lolmaus** [comment]
@rohan07 Please explain your goal, your attempted solution and what did not work for you.

**Comment by rohan07** [comment]
@lolmaus Thanks for your prompt reply. I am trying to make the error style a solid underline. I know that they use a background image so my first step was to remove the image being used. However, that doesn't work. I set the property of background-image to be none in the CSS,

**Comment by rohan07** [comment]
Works! Thanks a lot, @lolmaus!

**Comment by ianizaguirre** [comment]
> @rohan07
> 
> ```css
> .monaco-editor .squiggly-error {
>     background: none !important;
>     border-bottom: 2px solid red;
> }
> ```

Thank you for this! How would you target the font color of that error, since just using `color: yellow !important` inside that rule does nothing ?

**Comment by ianizaguirre** [comment]
This was my end result in VS Code:

![vscode-squiggly-error-to-outline-error](https://user-images.githubusercontent.com/29879270/48297096-a3c60800-e46e-11e8-8593-7b2b5b4a0a43.png)

```css

.monaco-editor .squiggly-error {
    border: 1px solid red;
    border-bottom-width: 2px;
    border-radius: 3px;
    background: none !important;
    background-color: RGBA(255, 97, 136, 0.5) !important;
}
```

**Comment by ctf0** [comment]
also https://stackoverflow.com/questions/43935303/show-gutters-for-errors-in-vscode/55912141#55912141

**Comment by craigcosmo** [comment]
@lolmaus how about warning? like this

```
.monaco-editor .squiggly-warning {
    background: none !important;
    border-bottom: 2px solid red;
}
```
