### ISSUE TITLE
Problem on VSCode v. 1.22.2

### ISSUE THREAD

**Issue by IronTony** [be5invis/vscode-custom-css#39]
Hi,

I am working with VS Code v.1.22.2 on Mac High Sierra and unfortunately I am not able to configure this extension.

I have my `vscodestyles.css` file inside a folder in Documents, so I used this path inside the User Settings: `"vscode_custom_css.imports": ["file://Users/legolas/Documents/VSCode-style/vscodestyles.css"]`
Then in my project I use the command: `Reload Custom CSS and JS`, so I can see the paint basket in the Visual Studio Code bottom bar, but the styles are not applied.

This is my file configuration:
```
.type.storage,.type.storage.declaration, .storage.class.modifier {
  font-family: 'Script12 BT';
  font-size: 1.7em;
}

.type.storage.arrow.function {
  font-family: 'Fira Code'
}

.decorator.name, .decorator.punctuation:not(.block), .import.keyword {
    font-family: 'Script12 BT';
    font-size: 1.7em;
    color: #68f39b!important;
}
.attribute-name {
    font-family: 'Script12 BT';
    font-size: 1.5em;
}

.html.quoted.double {
    color: #a6f3a6!important;
}

.comment {
	color: #c5c5fd!important;
}
.comment:not(.punctuation) {
    font-family: 'Script12 BT';
    font-size: 1.5em;
}
```

Any help will be more than appreciated.
Thank you

**Comment by be5invis** [comment]
VSCode **does not** use syntax classes in their UI directly (they do some complex conversion).
You need to either write a syntax file or update your CSS with the help of dev tools.

**Comment by IronTony** [comment]
Thank you, I am new to VSC.

**Comment by Dsupreme** [comment]
I guess you were referring to this blog post
[https://medium.com/@zamamohammed/multiple-fonts-alternative-to-operator-mono-in-vscode-7745b52120a0](url)

I am also facing the same issue with v1.22

In the developer tools the keywords `import` and `from` etc, have a class `mkt7`

Not sure how to proceed.

**Comment by bvaughn** [comment]
I have also experienced this. (OS X, VS Code 1.22.2)

Custom styles are not loaded, but I'm also not seeing any errors in the developer console.

I have installed a custom grammar plugin (Babel) in case that's related.

**Comment by gusbemacbe** [comment]
@IronTony, you did a mistake.

You used `file://`. The correct is `file:///`. Read my instructions in another: https://github.com/be5invis/vscode-custom-css/issues/40#issuecomment-386664216
