### ISSUE TITLE
Doesn't work anymore after updating to VS Code 1.23.0

### ISSUE THREAD

**Issue by gmaggio** [be5invis/vscode-custom-css#40]
After updating to VS Code 1.23.0 the add-on doesn't seem to work anymore.

**Comment by be5invis** [comment]
Every time Code updates there would be an issue...

Do you see the small bucket on the status bar?
Are you using CSS to style editor tokens?
Are you correctly configured the file URLs?

**Comment by gmaggio** [comment]
Yes, I did.

Just wondering, are you not having the same issue after the update? Or is it just my editor?

**Comment by gmaggio** [comment]
I'm on iOS...

How do you run the "re-activate" command with proper permission?

**Comment by gusbemacbe** [comment]
He may have confounded iOS with macOS.

**Comment by be5invis** [comment]
One possibility is Code moved some of its internal files to somewhere else. I do not have Mac. The plugin worked well on Windows.

**Comment by gusbemacbe** [comment]
Here, on my macOS, it worked well. That didn't work for them because they used `file://` instead of `file:///`

Put the tld;dr and simple instructions for macOS like:

1. Install this extension.
2. Add to s`ettings.json`:

```json
    "vscode_custom_css.imports": [""],
    "vscode_custom_css.policy": true,
```

3. Pay attention:

file:// + /User/yourname/path/to/css = file:///User/yourname/path/to/css

3. Close the VSCode and open the terminal and run a command:

For VSCode:
```shell
sudo chown -R $(whoami) '/Applications/Visual Studio Code.app/Contents/MacOS/Electron'
```

For VSCode Insiders:
```shell
sudo chown -R $(whoami) '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron'
```
4. Open VSCode, press Cmd+Shift+P, type "Reload CUSS CSS and JS" and select it.
5. Restart.
6. Voilà.

**Comment by gusbemacbe** [comment]
@be5invis, see how my instructions for macOS users. Update your README. Let's close the issue as he has already solved the issue.

**Comment by NikhilSaini38** [comment]
same issue css is not being reflected
steps done
1. Install plugin,
2. Create Css file
3. Added to imports with 'file:///' url
4. Bucket is visible

**Comment by NikhilSaini38** [comment]
sorry forgot to mention that, did that already

**Comment by gusbemacbe** [comment]
Therefore you need to become the app as user instead of root before reloading the app.

**Comment by NikhilSaini38** [comment]
i did the same

**Comment by NikhilSaini38** [comment]
does it have anything to  do with xorg?

**Comment by NikhilSaini38** [comment]
Followed everything to the exact, still no styling

**Comment by gusbemacbe** [comment]
@NikhilSaini38 and for Linux users

1. Go to `/home/your_name/.vscode` (for VSCode) or `/home/your_name/.vscode-insiders` (for VSCode Insiders) and create a new folder, naming `themes` and put a CSS file;
2. Open VSCode, open `settings.json` and add to `settings.json`:

For VSCode:

For VSCode Insiders:

```json
    "vscode_custom_css.imports": ["file:///home/yourname/.vscode/themes/your_css.css"],
    "vscode_custom_css.policy": true,
```

For VSCode Insiders:

```json
    "vscode_custom_css.imports": ["file:///home/yourname/.vscode-insiders/themes/your_css.css"],
    "vscode_custom_css.policy": true,
```

3. Close the VSCode and open the terminal and run a command:

For VSCode:

```
sudo chown -R $(whoami) /usr/share/code
```

For VSCode Insiders:

```
sudo chown -R $(whoami) /usr/share/code-insiders
```

4. Open VSCode, press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, type "Reload CUSS CSS and JS" and select it.
5. Restart.
6. Voilà.

**Comment by NikhilSaini38** [comment]
Did a fresh vscode install after purging all data related to vscode, and followed above steps exactly. Still not working.

**Comment by gusbemacbe** [comment]
What is your VSCode verison?

Type `code --version` or `code-insiders --version`

**Comment by NikhilSaini38** [comment]
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T16:04:33.747Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by be5invis** [comment]
If the bucket icon is visible then the plugin is working. You should check whether your URL of the CSS is really a URL and it really points to your style file.
Are there any logs in the Dev tool ?

**Comment by NikhilSaini38** [comment]
bucket icon is visible , Url opens correct file in chrome, so i guess it is also correct. About dev tool i'll tell

**Comment by NikhilSaini38** [comment]
dev tools are not showing any error, i used css from this page
https://medium.com/@zamamohammed/multiple-fonts-alternative-to-operator-mono-in-vscode-7745b52120a0
```
.type.storage,.type.storage.declaration, .storage.class.modifier {
  font-family: 'flottflott';
  font-size: 1.7em;
}

.type.storage.arrow.function {
  font-family: 'Fira Code'
}

.decorator.name, .decorator.punctuation:not(.block), .import.keyword {
    font-family: 'flottflott';
    font-size: 1.7em;
    color: #68f39b!important;
}
.attribute-name {
    font-family: 'flottflott';
    font-size: 1.5em;
}

.html.quoted.double {
    color: #a6f3a6!important;
}
.comment {
	color: #c5c5fd!important;
}
.comment:not(.punctuation) {
    font-family: flottflott;
    font-size: 1.5em;

```

**Comment by gusbemacbe** [comment]
You missed a closed brackets in the end of this CSS.

**Comment by be5invis** [comment]
@NikhilSaini38 
Another poor guy who styled tokens...
Styling tokens in this way are **NOT** supported anymore by Code many versions ago. The article is written in 2016, and the token styling support is **REMOVED** in 2017. Currently, tokens in Code uses a machine-generated class name associated to themes.

**Comment by NikhilSaini38** [comment]
that answers it i guess

**Comment by gusbemacbe** [comment]
Nikhil, as this theme is not supported as Belleve has aid, you can replace for Fira Code iScript, created by the same author of Fira Code. You do not need to apply a CSS, unless you want to style VSCode.

**Comment by gusbemacbe** [comment]
As you want to use an alternative to Operator Mono, you can try the theme: https://github.com/idbartosz/vscode-darkpp-italic

**Comment by NikhilSaini38** [comment]
Issue resolved, Thanks.

**Comment by gusbemacbe** [comment]
@NikhilSaini38 

Here are my previews. I use Nord, fonts Fira Code iScript and Overpass Mono, and besides, I added a CSS custom file, painting few areas:

![image](https://user-images.githubusercontent.com/2257024/40335256-1dc68fb6-5d39-11e8-9b35-c385e18bba7e.png)

![image](https://user-images.githubusercontent.com/2257024/40335278-34842880-5d39-11e8-8f2a-1263dc8594bb.png)

And my CSS custom is:

![image](https://user-images.githubusercontent.com/2257024/40335328-7557e306-5d39-11e8-9937-0e1bc2dccc49.png)

Observe the sentence in italic in the end and see how I applied only Fira Code iScript in `settings.json` without needing to readjust the fonts in a CSS custom file:

![image](https://user-images.githubusercontent.com/2257024/40335384-a798e676-5d39-11e8-9c49-a2a8b6df69d3.png)

**Comment by dncdrn** [comment]
> ```shell
> sudo chown -R $(whoami) '/Applications/Visual Studio Code.app/Contents/MacOS/Electron'
> ```

Im having a hard time to run this command
`sudo chown -R $(whoami) '/Applications/Visual Studio Code.app/Contents/MacOS/Electron'`
either this
`sudo chown -R $(whoami) '/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron'`

i have this error 
chown: /Applications/Visual Studio Code.app/Contents/MacOS/Electron: No such file or directory
or the other script
chown: /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron: No such file or directory

i ran this code in vscode terminal. Need some help @gusbemacbe thanks in advance!

**Comment by gusbemacbe** [comment]
@dncdrn

1. Go to the free `Applications`.
2. Find the app.
3. Open it, clicking with the property menu and selecting "Show Content Package".
4. Press <kbd>Cmd</kbd> + <kbd>F</kbd> and search "Electron". 
5. Copy the absolute path of found "Electron".

**Comment by dncdrn** [comment]
@gusbemacbe Thanks a lot! I was able to run the command without any error, unfortunately i cant still see the glow effect. After i run the command i reloaded the custom css and js loader, restart the vs code nothings happened 😞
