### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Prathik-Jain** [be5invis/vscode-custom-css#43]
- I get the paint bucket on my status bar.
- I gave the file URL
Still it doesn't seem to work.

**Comment by be5invis** [comment]
Any log in dev tools?
If you are styling tokens then it **should** not work since VSCode internally converts tokens into a machine-generated list of class names.

**Comment by Prathik-Jain** [comment]
`.mtk4` is the class that is generated internally.

**Comment by Prathik-Jain** [comment]
Is the issue solved yet?

**Comment by be5invis** [comment]
The extension cannot solve this since we have no idea how Code generates the `.mtk` classes. You need to update your CSS if the classes changed.
