### ISSUE TITLE
The path to the vs code files is different than what the readme says (on arch linux)

### ISSUE THREAD

**Issue by Emmatipate** [be5invis/vscode-custom-css#46]
I had to use `sudo chown -R $(whoami) /opt/visual-studio-code/` instead of  `/usr/share/code`. I installed using the AUR package [visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin).

**Comment by danidee10** [comment]
I'm not sure I understand you,
The command is used to change the owner of the root directory to the current user and it has to be entered in the terminal because it requires the password.

Can the extension automatically do that for us (I doubt it)?

Thanks

**Comment by be5invis** [comment]
Extension cannot.
So you are asking about update the doc?
ARRRGH...

**Comment by danidee10** [comment]
Yeah, I can open a PR if you want.

**Comment by pat-s** [comment]
Please put the custom path on Arch into the README.

**Comment by be5invis** [comment]
Fixed in 3.0.1.
