### ISSUE TITLE
插件没有效果

### ISSUE THREAD

**Issue by dev-itsheng** [be5invis/vscode-custom-css#47]
我按照文档上的说明，配置了如下的设置：

```json
{
    "vscode_custom_css.policy": true,
    "vscode_custom_css.imports": [
        "http://127.0.0.1/vscode.css"
    ]
}
```

VSCode 版本为 1.26.0-insider，操作系统版本为 Windows 10 专业版 Insider Preview 17711.1000

其中 vscode.css 路径一开始使用的是 file 协议，发现没有效果，又搭建了本地 HTTP 服务器，通过该 URL，在浏览器中可以正常访问。

结果插件不工作，在控制台检查样式，发现所定义的 CSS 没有引入。

望早日解决，谢谢。

**Comment by be5invis** [comment]
Is there a bucket icon in the status bar?
Every time you changed the config you have to re-enable the CSS via the commands.

**Comment by dev-itsheng** [comment]
不好意思，是我没有看清楚说明文档，目前问题已经解决，感谢
