### ISSUE TITLE
Problem with VSCode installed from Snap.

### ISSUE THREAD

**Issue by ris58h** [be5invis/vscode-custom-css#48]
What are steps to make it work in such environment?

Obviously there is no `/usr/share/code` but `sudo chown -R $(whoami) /snpa/bin/vscode` didn't help.

Are there any error/debug logs?

**Comment by be5invis** [comment]
You need to locate where the `electron-browser/bootstrap/index.html` is, and give permission to modify it and the directory containing it.

**Comment by ris58h** [comment]
Files inside Snap are read-only so it seems like it isn't possible to use this extension in this case.
Should it be added to README?

**Comment by be5invis** [comment]
Fixed in 3.0.1
