### ISSUE TITLE
Quick minor question. What's the name of the color scheme that you use in the snapshot in the readme?

### ISSUE THREAD

**Issue by jcklpe** [be5invis/vscode-custom-css#50]
It's a nice looking scheme and I was curious.

**Comment by be5invis** [comment]
Railgun Corona.

**Comment by jcklpe** [comment]
Thanks!

**Comment by jcklpe** [comment]
@be5invis Also sorry to bother with a second question but what's the name of the font you use in it? I don't see it defined in the theme.

**Comment by be5invis** [comment]
Iosevka.

**Comment by jcklpe** [comment]
Thanks again!
