### ISSUE TITLE
Not working on v1.28

### ISSUE THREAD

**Issue by fabiospampinato** [be5invis/vscode-custom-css#54]
OS: macOS v10.13.5
VSCode: v1.28

I did what the readme said, I've executed:

```
sudo chown -R $(whoami) '/Applications/Visual Studio Code.app/Contents/MacOS/Electron'
```

But this extension is still complaining. Can you fix that?

**Comment by adamk22** [comment]
It also doesn't seem to work on my system (same os/vscode) version. I'm getting `command 'extension.installCustomCSS' not found` if I try to enable or reload custom css and js. Are you getting something similar?

**Comment by fabiospampinato** [comment]
It's working again for me under v1.28.2.

> command 'extension.installCustomCSS' not found

this should happen only when the extension isn't active 🤔
