### ISSUE TITLE
ERR EROFS: read-only file system

### ISSUE THREAD

**Issue by Recodify** [be5invis/vscode-custom-css#55]
I'm trying this plugin with vscode that was installed via snap and am getting the following.

![image](https://user-images.githubusercontent.com/5644228/47903498-b1322f80-de7b-11e8-8608-5f93ae452829.png)

I believe this is because /snap is mount as a read-only volume?

**Comment by be5invis** [comment]
This plugin modifies Code so you have to start Code in a way that it can modify itself.

**Comment by knkbga** [comment]
> I'm trying this plugin with vscode that was installed via snap and am getting the following.
> 
> ![image](https://user-images.githubusercontent.com/5644228/47903498-b1322f80-de7b-11e8-8608-5f93ae452829.png)
> 
> I believe this is because /snap is mount as a read-only volume?

I am also facing this issue. Were you able to figure out how to resolve this. Thanks

**Comment by Perodactyl** [comment]
I don't believe this should be "completed." How exactly should I start vscode in a way that it can modify itself?
