### ISSUE TITLE
Document "Update Custom CSS and JS" command

### ISSUE THREAD

**Issue by mikewheaton** [be5invis/vscode-custom-css#6]
First of all, thank you for this extension! The only frustration I've had is that the documentation does not mention anything about the "Update Custom CSS and JS" command. My custom styles stopped working for some reason, and I kept restarting VS Code thinking that was the only way to reload the styles. Eventually, I found a blog post that mentioned this command and it fixed the issue. I think this should be included under [extension commands in the README](https://github.com/be5invis/vscode-custom-css#extension-commands).

**Comment by valentinocossar** [comment]
+1

**Comment by be5invis** [comment]
It is just disable and then re-enable

发自我的 iPhone

在 2018年2月2日，03:26，Valentino Cossar <notifications@github.com<mailto:notifications@github.com>> 写道：


+1

**Comment by valentinocossar** [comment]
Yes, but I think the Update command should be reported in the README. Also, people should know that after every change to custom files, they have to run the Update command and reload VS Code to see changes.
