### ISSUE TITLE
"Operation not permitted" error in VS Code 1.30.1, Windows 10

### ISSUE THREAD

**Issue by dannymcgee** [be5invis/vscode-custom-css#64]
Had this working like a charm before the update.

**Steps:**
1. Run VS Code as Administrator, click Yes on the UAC dialog
2. Use the command palette to run "Enable Custom CSS and JS" or "Reload Custom CSS and JS"

**Result:**
1. A VS Code notification is received in the bottom right corner: "Run VS Code with admin privileges so the changes can be applied."
2. A console error is logged in the developer tools: 
`ERR EPERM: operation not permitted, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\workbench.html.bak-customcss': Error: EPERM: operation not permitted, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\workbench.html.bak-customcss'`

Let me know if you need anymore information!

**Comment by dannymcgee** [comment]
I forgot about an important step here: Before you open VS Code as Administrator, you need to **close all running instances**. If you already have an instance of VS Code running, you can't run a _new_ instance as Administrator. Closing this issue!

**Comment by ranapartap** [comment]
VScode Ver 1.85.1, Smae error for non Administrator mode. Css file is not loading.
