### ISSUE TITLE
A weird Prompt

### ISSUE THREAD

**Issue by TharunThabeti** [be5invis/vscode-custom-css#66]
Hello,
I followed every single step. But when I tried to run "Enable Custom CSS and JS" command I got a prompt "Your Code installation appears to be corrupt. Please reinstall.". 
![2019-01-02](https://user-images.githubusercontent.com/38430695/50589591-4e760800-0ead-11e9-96e1-4499e1a52615.png)

**Comment by be5invis** [comment]
![image](https://user-images.githubusercontent.com/240091/50589829-28f3f900-0ec3-11e9-8963-dd142fc973fe.png)
Just ignore that. This plugin replaces Code files so Code felt itself being modified. This is by design.

**Comment by TharunThabeti** [comment]
Yeah, but I'm not able to get the desired result, like a different font with italics on. I tried playing with the css file that I've created but none of them seems working.
![screenshot](https://user-images.githubusercontent.com/38430695/50589936-9b0e1300-0eae-11e9-9528-e0793da3eafc.png)

**Comment by be5invis** [comment]
What's your config?

**Comment by TharunThabeti** [comment]
Where should I apply styles permanently, If I get to know the classes?

**Comment by be5invis** [comment]
You need to write a CSS, add its **FILE URL** (NOT PATH, NOT PATH, NOT PATH) into your config, and re-enable styling.

**Comment by TharunThabeti** [comment]
Thanks, Can you help me with the theme you have posted on markdown? The name of theme?

THIS ONE ↓

![screenshot](https://user-images.githubusercontent.com/38430695/50591351-31ddce00-0eb5-11e9-89e1-a0c7263bb3f3.png)

**Comment by be5invis** [comment]
I do not have its files now :(
It has passed a long time

**Comment by TharunThabeti** [comment]
Any chance that I can get those files? On marketplace? Or it's just self made?

**Comment by be5invis** [comment]
Well it is just self-made by me :(
One example of the themes may be this: https://gist.github.com/Hendrixer/7a250a2be529cda8939de8305c9a85a1

**Comment by TharunThabeti** [comment]
Thanks!
