### ISSUE TITLE
can't make it work with snap installed vscode

### ISSUE THREAD

**Issue by guifelix** [be5invis/vscode-custom-css#68]
I have tried to follow the steps but it wont work at all... is there a solution for this problem or do I have to install vscode again?

**Comment by guifelix** [comment]
but in #48 it was said that the error was fixed

**Comment by be5invis** [comment]
No idea what happened. You can try to open F12 and display the logs.


________________________________
发件人: Guilherme Maciel <notifications@github.com>
发送时间: 星期六, 一月 26, 2019 20:38
收件人: be5invis/vscode-custom-css
抄送: Belleve Invis; Comment
主题: Re: [be5invis/vscode-custom-css] can't make it work with snap installed vscode (#68)


but in #48<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbe5invis%2Fvscode-custom-css%2Fissues%2F48&data=02%7C01%7C%7C32b2bc82580e4c975fe508d6838b1daf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636841030852711599&sdata=QeM%2FLYjELO9EA%2BNag0y9HifRRtqr8a0spFOiHyfVq8c%3D&reserved=0> it was said that the error was fixed

―

**Comment by filtration** [comment]
Snap uses a squashfs so it's readonly. You will need to install vscode somewhere else like 

/usr/share/code

Take a lot at this bash script if you want to manually install code: https://github.com/filtration/ubuntu-setup/blob/master/install/apps/code.sh

**Comment by CuriousFu** [comment]
today i upgrade my vscode , but enabling this extension causes the information as following picture:
