### ISSUE TITLE
[Possible Bug] `extension.updateCustomCSS` not found

### ISSUE THREAD

**Issue by prmichaelsen** [be5invis/vscode-custom-css#69]
### Reproduce
1. Install
2. Restart vscode
3. Run 
![image](https://user-images.githubusercontent.com/8428140/53385687-7e390d80-393c-11e9-8090-44326da0eb7f.png)

### Expected
Reloads custom css

### Actual
This error:
![image](https://user-images.githubusercontent.com/8428140/53385646-55b11380-393c-11e9-90a1-7622e1e7f53f.png)

**Comment by rafaelc0sta** [comment]
Found the error. The documentation doesn't say anything about it, but you should run `npm install` inside the extension directory, or else it will never load.

**Comment by prmichaelsen** [comment]
Ay caramba, thank you for the response. I will try this and then report back. If it works, I will open a PR to update the documentation.

**Comment by rafaelc0sta** [comment]
> Ay caramba, thank you for the response. I will try this and then report back. If it works, I will open a PR to update the documentation.

Already did! https://github.com/be5invis/vscode-custom-css/pull/73

:)

**Comment by be5invis** [comment]
Perhaps a packaging issue.

________________________________
发件人: Patrick Michaelsen <notifications@github.com>
发送时间: Tuesday, April 30, 2019 1:15:03 AM
收件人: be5invis/vscode-custom-css
抄送: Subscribed
主题: Re: [be5invis/vscode-custom-css] [Possible Bug] `extension.updateCustomCSS` not found (#69)


Ay caramba, thank you for the response. I will try this and then report back. If it works, I will open a PR to update the documentation.

―

**Comment by be5invis** [comment]
@rafaelc0sta @prmichaelsen 
Please try out whether v3.0.4 fixed this.
VSCE doesn't install dependencies by default which is bad for doc-only updates :(
