### ISSUE TITLE
Why should we install this?

### ISSUE THREAD

**Issue by john-aws** [be5invis/vscode-custom-css#71]
Neither the github repo nor the VS Code extensions page provides any reason, compelling or otherwise, for a user to install vscode-custom-css. Please consider documenting what this extension does and why we should consider installing it.

**Comment by acarlsten** [comment]
It allows you to modify the look of parts of VSCode that are otherwise hardcoded, such as the font in the Explorer sidebar or file tabs. I suppose it could be clearer, though.

**Comment by john-aws** [comment]
That's helpful, thanks. Not a big problem, obviously, but I think you may be missing an opportunity to advertise the value of your project. I only find out indirectly through [wesbos](https://github.com/wesbos/cobalt2-vscode).
