### ISSUE TITLE
Update documentation to include links to VSCode issue tracker

### ISSUE THREAD

**Issue by Yzrsah** [be5invis/vscode-custom-css#72]
Please include links to the VSCode issue tracker with open issues for supporting custom CSS without corrupted install.

**Comment by be5invis** [comment]
I am very sorry but I am currently very busy with my transfer to Redmond and do not have much time. PRs are welcome.

________________________________
发件人: Yzrsah <notifications@github.com>
发送时间: Thursday, March 21, 2019 12:42:07 AM
收件人: be5invis/vscode-custom-css
抄送: Subscribed
主题: [be5invis/vscode-custom-css] Update documentation to include links to VSCode issue tracker (#72)


Please include links to the VSCode issue tracker with open issues for supporting custom CSS without corrupted install.

―
