### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by arpitjain-in** [be5invis/vscode-custom-css#74]
Hi,

I tried my best to install and use "Synthwave84" theme into my VSCode. I did lots of time restart and all possible the possible ways to bring this up but I didn't succeed.

Please help! any suggestion.

**Comment by MayasHaddad** [comment]
@arpitjain-in I ran into a similar issue on Mac OS, I fixed this out of `Downloads/` directory to the `Applications/`

**Comment by SynAckPwn23** [comment]
I have the same issue... How to solve? I tried to change path as well without success.

**Comment by halink0803** [comment]
I got problem making it works too. I run the command `chown` but it keep telling me to run applications as administrator. Any one know how to solve?

**Comment by be5invis** [comment]
I do not have Mac machines.
Can anyone paste the F12 logs?

________________________________
发件人: Hoàng Hà <notifications@github.com>
发送时间: Saturday, May 4, 2019 12:41:08 PM
收件人: be5invis/vscode-custom-css
抄送: Subscribed
主题: Re: [be5invis/vscode-custom-css] Not working on Mac (#74)


I got problem making it works too. I run the command chown but it keep telling me to run applications as administrator. Any one know how to solve?

―

**Comment by joeydeeds** [comment]
I got it working on mac by following the readme here and readme for synthwave84. vscode version 1.33.1 and mojave version 10.14.4

**Comment by halink0803** [comment]
I got it working by using file:///... url. import directly web url does not work.
