### ISSUE TITLE
Debug procedures for CSS not being reflected?

### ISSUE THREAD

**Issue by VVVFO** [be5invis/vscode-custom-css#78]
Hi I'm trying to install the Synthwave theme and followed the installation procedures. I

1. Did chown and restart (multiple times)
2. Ensured that the file exists (using `file:///`, and Command click does open the file)
3. Can see the bucket icon
4. Don't think there's any issue with the CSS file itself as I am just using [the one provided by Synthwave](https://github.com/robb0wen/synthwave-vscode/blob/master/synthwave84.css)

But the CSS is still not reflected, any idea? (VSCode Version 1.33.1, macOS 10.14.4)

**Comment by bkno** [comment]
Same problem... just can't get it to display.
