### ISSUE TITLE
it really doesn't work

### ISSUE THREAD

**Issue by ChaseChan** [be5invis/vscode-custom-css#79]
vscode version: 1.33.1

command: sudo chown -R $(whoami) /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron 

when i finished, it still has tips below:

**Run VS Code with admin privileges so the changes can be applied.**

em,when i reload, nothing changes.

below is my settings.json config
```
{
    "vscode_custom_css.imports": [
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.css",
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.js"
    ],
    "vscode_custom_css.policy": true,
    "terminal.integrated.rendererType": "dom"
}
```

**Comment by seanfuture** [comment]
Works for myself ( just tested ) after running:

`sudo chown -R $(whoami) "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"`

Personal settings.json file includes:

    "vscode_custom_css.imports": [
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.css",
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.js"
    ],
    "vscode_custom_css.policy": true,

Make sure to use the command "Enable Custom CSS and JS" and also verify that your theme files are owned by $(whoami) and you have access to those files, naturally.  After running this command please report any errors visible either on screen or in console and from which source ( alert or console ) where the error was reported.

You may also wish to test via running VSCode from the command line under `sudo`

**Comment by karenclo** [comment]
@ChaseChan It originally wasn't working for me either, but I noticed @seanfuture had quotes around the path. After using that command everything worked :)
