### ISSUE TITLE
Not working in VS Code 1.9.0

### ISSUE THREAD

**Issue by mikewheaton** [be5invis/vscode-custom-css#8]
After updating to VS Code 1.9.0 the extension is no longer working. When I run the "Update Custom CSS and JS" command I'm now forced to restart Code:

![image](https://cloud.githubusercontent.com/assets/1382445/22619869/9f1622e8-eab2-11e6-8f9f-280ff6e43512.png)

And after restarting I'm warned that Code is corrupt:

![image](https://cloud.githubusercontent.com/assets/1382445/22619880/bb1638ac-eab2-11e6-810a-8e6e10547662.png)

**Comment by jens1o** [comment]
Same problem here. The repo seems to be unmaintained :/

**Comment by be5invis** [comment]
No, this is **NORMAL** because the plugin actually **modifies** VSCode's installation.

**Comment by jens1o** [comment]
and how can we proceed with our customazation?

**Comment by be5invis** [comment]
@jens1o Simply, click "don't show again".
This extension **modifies** VSCode itself, so this message is always shown. It is a by-design.
