### ISSUE TITLE
Win10 Admin privileges not recognized

### ISSUE THREAD

**Issue by xoorath** [be5invis/vscode-custom-css#80]
Launching vs code as admin doesn't let me enable the plugin. For reference, I was able to install just fine on my home PC but here at my work I'm unable - so I don't believe it's user error but probably something permissions related.

Here are the steps I took:
- I installed the extension from vscode
- right clicked on the vscode icon on my desktop and ran as administrator.
- accepted the windows popup  (do you want to allow this app to make changes to your device?)
- vscode launched as expected.
- ctrl+shift+p to open the pallete and I selected "Enable Custom CSS & JS"

At this point I got the same popup I would get if I wasn't running as admin "Run VS Code with admin privileges so the changes can be applied."

**Comment by donnisnoni95** [comment]
@xoorath migrate to linux

**Comment by xoorath** [comment]
Lol cheeky, @donnisnoni95.

**Comment by groussel42** [comment]
I same the same probleme on VSCode **Insider** but it works perfectly on the regular one

**Comment by ktmn** [comment]
I get this in the console when trying to activate as admin:

```
[Extension Host] vscode-customcss is active!
console.ts:137 [Extension Host] activated
log.ts:196   ERR ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\bootstrap\index.html': Error: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\bootstrap\index.html'
log.ts:196   ERR ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\bootstrap\index.html.bak-customcss': Error: ENOENT: no such file or directory, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\electron-browser\bootstrap\index.html.bak-customcss'
```

`resources\app\out\vs\workbench\electron-browser` does not exist.
`resources\app\out\vs\code\electron-browser` exists, no `bootstrap` there though.
There's an `index.html` at `resources\app\out\vs\workbench\contrib\webview\browser\pre`, would that work?
