### ISSUE TITLE
Mac OS - Run VS Code with admin privileges so the changes can be applied

### ISSUE THREAD

**Issue by Hugofsp93** [be5invis/vscode-custom-css#83]
I can't reload ou enable the custom css and js. 

A warning show up:
"Run VS Code with admin privileges so the changes can be applied" 
and i just cannot enable to use the synthwave84 extension.

"vscode_custom_css.imports": [
        "file:///Users/myuser/Documents/synthwave84.css",
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.css",
        "file:///Applications/Visual Studio Code.app/Contents/Resources/theme/custom.js"
    ],
    "vscode_custom_css.policy": true,

**Comment by ZXMLoveCXF** [comment]
Have you solved this problem?

**Comment by ZXMLoveCXF** [comment]
How do you solve this problem?

**Comment by RezhaBlue** [comment]
running into the same issue, this was closed with no explanation or anyone addressing it.
I have tried both wsl and windows using sudo and run as admin respectively but the extension continues to assert I need to run vs code with admin privileges. This seems like a bug to me.
