### ISSUE TITLE
causing corrput on the vscode version 1.35

### ISSUE THREAD

**Issue by CuriousFu** [be5invis/vscode-custom-css#84]
If enabled, then the following information appears at the startup of the vscode 1.35,
vscode 1.34 works ok.
```
Your VSCodium installation appears to be corrupt. Please reinstall.
```
```
[UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
```

**Comment by Al2Me6** [comment]
Seconded,

vscode 1.35 on Manjaro Linux with AUR script.

Enabling CSS injection causes an extra error to occur, resulting in the failure to display image previews.

Output without CSS injection:

![image](https://user-images.githubusercontent.com/35266431/59236253-54da7f80-8bc3-11e9-8d28-f264dd5346fc.png)

Output with CSS injection (additional error highlighted):
![image](https://user-images.githubusercontent.com/35266431/59236301-83585a80-8bc3-11e9-9f38-b364d2a9b048.png)

**Comment by danielmain** [comment]
Using the official VSCode I get the same problem

Version 1.36.1 (1.36.1)
Mac OS X

**Comment by be5invis** [comment]
“Corruption” is **expected behavior** because this extension modifies Code itself to inject your CSS into it.

**Comment by al2me6** [comment]
@be5invis it seems that I am seeing a different problem than the other posters here. I'll open another issue.
