### ISSUE TITLE
VSCode 1.37 - Custom CSS suddenly not being applied

### ISSUE THREAD

**Issue by willstocks** [be5invis/vscode-custom-css#89]
Hello!

I had an update for VSCode this morning (1.37) and have noticed that custom CSS is no longer being applied.

I use the Synthwave glow theme, so it's fairly noticeable.

If I "Reload Custom CSS and JS", I get the notification to restart VSCode. I restart and nothing changes. I still get the "Your Code installation appears to be corrupt" error though :(

If I check the devtools console, I see:

```
[Extension Host] vscode-customcss is active!
[Extension Host] Looking for parseable documents...
[Extension Host] Found no documents
```

I have not changed my settings.json (which was working fine on Friday) which has:

```json
{
  "vscode_custom_css.imports": [
    "https://cdn.jsdelivr.net/gh/robb0wen/synthwave-vscode@master/synthwave84.css"
  ],
  "vscode_custom_css.policy": true
}
```

**Comment by willstocks-tech** [comment]
Please ignore... it seems that for some reason it related to the URL being used (which works fine...)

I am now using:

```json
{
  "vscode_custom_css.imports": [
    "https://raw.githubusercontent.com/robb0wen/synthwave-vscode/master/synthwave84.css"
  ],
  "vscode_custom_css.policy": true
}
```
and it is working perfectly fine. Not sure what is going on when using the jsdelivr URL...

**Comment by willstocks-tech** [comment]
Reopening as it _only_ seems to work for that one URL for me!!!

I have just changed to:

```json
{
  "vscode_custom_css.imports": [
    "https://raw.githubusercontent.com/willstocks-tech/synthwave-glow-plus-bracket-glow/master/styles.css"
  ]
}
```

and now I'm not seeing custom css being applied again and the original "errors" are being logged:

[Extension Host] vscode-customcss is active!
[Extension Host] Looking for parseable documents...
[Extension Host] Found no documents

**Comment by willstocks-tech** [comment]
I changed the file name (thinking maybe styles.css as a name was causing an issue) If I reload custom JS and CSS:

```
[Extension Host]% 
{imports: Array(1), statusbar: true, policy: false}
imports: Array(1)
0: "https://raw.githubusercontent.com/willstocks-tech/synthwave-glow-plus-bracket-glow/master/wssynthwaveglow.css"
length: 1
__proto__: Array(0)
policy: false
statusbar: true
__proto__: Object
```

But the styles still do not get applied!

But I'm immediately prompted to restart VSCode. When I do, I then get the following again immediately:

```
[Extension Host] vscode-customcss is active!
[Extension Host] Looking for parseable documents...
[Extension Host] Found no documents
```

**Comment by willstocks-tech** [comment]
I have also tried with `policy:true` but still the same :(

**Comment by willstocks-tech** [comment]
Works fine if the exact same file is local... and works fine for the version hosted on GitHub in the synthwave source repo... just doesn't seem to work if stored elsewhere????

**Comment by willstocks-tech** [comment]
I've implemented a bit of a "fallback" solution - if it can't reach the remote file, I'll just use the local version:
{
  "vscode_custom_css.imports": [
    "https://raw.githubusercontent.com/willstocks-tech/synthwave-glow-plus-bracket-glow/master/styles.css",
    "file:///C:/Temp/localstyles.css",
    "file:///Users/willstocks-tech/Documents/vscode/theme/localstyles.css
  ]
}

But the URL still doesn't load. The fallback does each time I open vscode at the moment 😞

**Comment by willstocks-tech** [comment]
@be5invis / @reli-msft - please see comment below from VSCode contributor on https://github.com/microsoft/vscode/issues/79115

>Extension that you've mentioned uses custom npm package to perform network requests
https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L6
>
>And that package has long standing issue with env variables driverdan/node-XMLHttpRequest#149
>
>Most likely extension should be switched correct implementation.

**Comment by be5invis** [comment]
+ @kasperfred

**Comment by be5invis** [comment]
I didn’t write the remote loading. Add back the original author.

**Comment by kasperfred** [comment]
If it's the case that it's the library that's causing the issue, rewriting the [`httpGet()`](https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L30-L38) method to not use the library should resolve the problem. 

I'm currently busy with other projects, so I can't do it myself right now, but you're free to have a go at it.

**Comment by willstocks-tech** [comment]
If it's any use, I use another plugin (code-settings-sync) which makes requests out to GitHub and I don't have any issues behind a corporate proxy with that plugin. You can see how it caters for environmental variables [here](https://github.com/shanalikhan/code-settings-sync/blob/master/src/service/github.service.ts) using [this](https://www.npmjs.com/package/https-proxy-agent) package.

That being said, I don't know if that also fits with the "correct implementation" suggested by the VSCode team??
>Most likely extension should be switched correct implementation.

**Comment by mmattocks** [comment]
> ```
> [Extension Host] vscode-customcss is active!
> [Extension Host] Looking for parseable documents...
> [Extension Host] Found no documents
> ```

Could you tell me how this output was produced? My extension host log looks like this:

```
[2019-09-02 07:07:35.999] [exthost] [info] ExtensionService#_doActivateExtension be5invis.vscode-custom-css {"startup":true,"activationEvent":"*"}
[2019-09-02 07:07:35.999] [exthost] [info] ExtensionService#loadCommonJSModule /home/main/.vscode/extensions/be5invis.vscode-custom-css-3.0.4/src/extension
```
And does not contain any information about what css documents have been loaded. Thanks!

**Comment by willstocks** [comment]
@mmattocks - `Ctrl` + `Shift` + `P` -> Toggle DevTools

**Comment by mmattocks** [comment]
> @mmattocks - `Ctrl` + `Shift` + `P` -> Toggle DevTools

Thanks! I switched to linux mint recently and the synthwave style stopped working- no idea why and the output here doesn't give any clues. Do you presently have it working with 1.37?

**Comment by willstocks** [comment]
@mmattocks - a bit off topic if you aren't having the same error, but: are you referring to the Synthwave theme styles, or the extra "glow" styles? You don't need custom CSS for the included styles, only the glow. The only other thing is have you definitely saved the styles down locally (or linked to them) and have you done so when running VSCode as admin (`sudo` in your case)

**Comment by willstocks** [comment]
Note - also affects JS (which is slightly more annoying than the lack of CSS applied!).

Any thoughts/progress/alternatives/workarounds for this one (working in a corporate/proxy environment) @be5invis, while @kasperfred is unavailable?
