### ISSUE TITLE
Not compatible with VS code version 1.10.2

### ISSUE THREAD

**Issue by JamDeezy** [be5invis/vscode-custom-css#9]
This extension is not compatible with VS code version 1.10.2. It may be the same issue as PR #8, as the only time I can get this to work is to install 1.8.

Sample CSS that would've worked in 1.8.
````
.editor-container .storage.type.function.arrow,
.editor-container .keyword.operator {
    font-family: 'Fira Code' !important;
}
````

**Comment by be5invis** [comment]
@JamDeezy Simply, click the "don't show again" on the "Your install is corrupted" message.
This extension **modifies VSCode itself** in order to make it able to load your custom CSS and JS.

**Comment by made-aryadinata** [comment]
@JamDeezy , the CSS is not working because those classes do not exist anymore.
They are replaced by `mtk` classes.

This is working for me (tried in javascript file only):
```.editor-container .mtk13
    font-family: 'Fira Code' !important;
}```

**Comment by JamDeezy** [comment]
@made-aryadinata the `.mtk13` class isn't working for me.

Is there any documentation on how they changed these classes? I'd like to target specific keyword for this font.

**Comment by made-aryadinata** [comment]
@JamDeezy use inspect element in Help > Toggle Developer Tools to see the class.

**Comment by JamDeezy** [comment]
@made-aryadinata thank you! `.mtk14` was the class I used for `.keyword.operator` and `.storage.type.function.arrow`

**Comment by teknologist** [comment]
The classes change and they don't scope correctly. For example, if "const" and "=>" have the same class... Changing themes and reloading VSCode also changed th.mkt12 to .mkt7

I don't think those mkt classes are a reliable identifier to use ligatures on specific keywords...

Waiting for a solution...

**Comment by jkchuynh829** [comment]
VSCode .mtk classes are generated from parsing the .tmTheme file. Inspect your TM scopes to find out what you need to edit in the .tmTheme file. For me, this meant adding an extra <dict> block that modifies my storage.type.function scope (for arrow functions). I changed the color slightly so that VSCode will create a new .mtk class for that scope, inspect with your VSCode Developer Tools to determine what that new class is. Specify that in your custom css file, and you should be good!

**Comment by teknologist** [comment]
@jkchuynh829 Thanks! works like a charm !

**Comment by formspoint** [comment]
> const and => both are fall under the storage.type scope, so you have to further specify storage.type.function to grab just the arrow function and VSCode will generate different classes for each.

Is there some docs somewhere detailing information like this?

**Comment by wecarrasco** [comment]
The arrow function in vscode has the class mtk11, so the css should go like this:
.mtk11 {
  font-family: "Fira Code" !important;
}

**Comment by isabelacmor** [comment]
Another route (which I had to take) was to add a textMateRule in my user settings:

`"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "storage.type.function.arrow",
        "settings": {
          "foreground": "#5fb3b3" // setting this color here overrides the styles font back to the default Fira Code
        }
      }
    ]
  }`
