### ISSUE TITLE
Using custom CSS in a VSCode theme extension

### ISSUE THREAD

**Issue by mkanet** [be5invis/vscode-custom-css#90]
Thank you so much for this extension. 

I made some css customizations to my vscode setup.  I like these customizations so much, Id like to include these customizations in my published theme extension.

Would it be okay to do this?  If so, what's the easiest possible way to integrate this capability to my extension.. so I only need to install my theme to get these customizations?

Thanks again!

**Comment by be5invis** [comment]
The injected CSS applies to the entire workbench. So you can easily apply them to extensions' UI.

**Comment by lunelson** [comment]
@be5invis could you clarify what you mean here? I was about to ask a similar question: since VSCode themes allow specifying `extensionDependencies` and `contributes` keys, is there a way that a theme extension could require your extension as a dependency, and contribute CSS rules to it?
