### ISSUE TITLE
Css not loading no matter how many times I restart

### ISSUE THREAD

**Issue by Sylenss** [be5invis/vscode-custom-css#95]
In my settings json file in visual studio code i have the two css 
"vscode_custom_css.policy": true, 

and I have where the file is located 
 "vscode_custom_css.imports": [
    "file:///Users/sylens/Desktop/vsc.css"
  ],

everytime i reload the css file that contains the content like this 
<img width="1680" alt="Screen Shot 2019-09-15 at 4 52 25 AM" src="https://user-images.githubusercontent.com/45975952/64919074-a3745880-d774-11e9-83a0-51ab2319b918.png">

reload & restart the changes and not being applied 
<img width="1680" alt="Screen Shot 2019-09-15 at 4 53 03 AM" src="https://user-images.githubusercontent.com/45975952/64919085-c6067180-d774-11e9-92f2-1663714321f4.png">

Ive been trying to figure out what the problem is the file is visible when i cmd + click inside my json settings Im currently on visual studio code version 1.38

**Comment by joseeloren** [comment]
Downgrade the version of enable custom CSS extension. Last version is broken because data addition.

**Comment by joseeloren** [comment]
Also calle Reload Custom CSS command.

**Comment by Sylenss** [comment]
@joseeloren Ive done that reload command just didnt upload the screenshot i found a solution downgrading was the fix thanks for the help.
